### ISSUE TITLE
Help text for TOC field

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#10]
Is it difficult to allow for formatting/spacing in the Description field? There are some objects for which the students wanted to add the table of contents into the description field, but the display looks terrible because of spacing issues. If it's too difficult to set up, we can forgo this.

**Comment by scande3** [comment]
Going to fix this soon but should it instead be a "table of contents" field to distinguish the type of data? This would essentially use this predicate: http://dublincore.org/documents/dcmi-terms/#terms-tableOfContents

**Comment by kjrawson** [comment]
Description is a broader container, so it has wider application. While adding TOC would often capture what we'd need, I can imagine other times when it would still be helpful to be able to format the Description field. If it's too complicated, we can use the Description field as we have it and a formatted TOC. I am realizing that this will also have implications for the display, since Description is currently displayed in records as a subheading, of sorts. We may need to move that down lower. I am happy to talk about this more, too––I am not strongly attached to any one solution. Thanks!

**Comment by scande3** [comment]
Added support for a "Table of Contents" field that will separate on "--". This is based on the way MARC does line breaks in examples of:

https://www.loc.gov/marc/bibliographic/concise/bd505.html
http://www.lib.noaa.gov/cataloging/Cataloging_Manual/505.html

Let me know how that looks (including where it should be placed) and what help text the element might have. Hopefully this works.

For the "Description" field, can you provide more information on its formatting? For example, is it just the same line break splitting only?

**Comment by kjrawson** [comment]
I've finally had time to test this out: https://www.digitaltransgenderarchive.net/files/xw42n7888. The display formatting is working well. Do you think it looks okay? 

Here's the help text I've drafted so far for the MAP: 

**Definition**: A list of subunits of the content of the resource.
**Requirement**: Optional
**Occurrence**: Non-Repeatable
**Schema**: None
**DC Terms**: tableOfContents
**Input Guidelines**:
- Free text. Use punctuation to make the value clear.
- To add a line break, insert a double en-dash (“--").
- When a description of a resource consists of a list of the contents, whether from a menu or other mechanism, tableOfContents can be used to differentiate this list from descriptive text that is written in sentence form.

**Examples**:
Table of Contents = Part 1 -- Mr. Fun Hog -- Hurricane Ethel -- After the Bath --The Failures of Milk -- Come Down in Time

**Comment by scande3** [comment]
The hep text should have been updated for this. Commit 336863bf14db614b4b45334b1858211750a8ae9b .

**Comment by kjrawson** [comment]
Thanks!
