### ISSUE TITLE
Autofill for publisher

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#101]
Even though we don't facet by publisher, the students asked if that field could include an autocomplete so that there would be more normalization of their data. Thanks!

**Comment by scande3** [comment]
This should now be working. Beyond the autocomplete, I also added a Publisher facet to the Files listing page. There is a link that will take one to an alphabetical list of publishers there. That link is: https://www.digitaltransgenderarchive.net/dashboard/files/facet/publisher_ssim

For example, looking at the list, there are three different spellings for: "Lee's Mardi Gras Interprises, Inc."

Added in commit 47ce1fb0bc2d61519c328f4614b62b8958842f1e . Let me know if there is more needed for this that might make it better. Thanks!

**Comment by kjrawson** [comment]
Thanks for this, Steven! The facet on the Files page and the alphabetical list to publishers is very helpful. The type ahead doesn't seem to be working, though. 

We've definitely got some cleaning up to do!

**Comment by scande3** [comment]
Sorry about that - forgot to recompile the javascript. Try it again now to see if it works? Thanks!

**Comment by kjrawson** [comment]
Works perfectly. Thank you!!
