### ISSUE TITLE
Batch harvest for Harvard

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#103]
Hey, Steven! 
I just heard from some folks at Harvard's Schlesinger Library that they have a batch of materials for us to harvest: http://via.lib.harvard.edu/via/deliver/deepLinkResults?kw1=mc614*&repositoryLimit=Schlesinger%20Library%20on%20the%20History%20of%20Women%20in%20America&index1=Anywhere

I wanted to check in with you about how much time it might take you to allow us to harvest this collection. It's 119 items, so it may not be worth it, but I figured I'd check. We can always do it manually. They said they can create a set of records from LibraryCloud through an open API and can provide metadata in XML or JSON format.

Thanks!

**Comment by scande3** [comment]
I'd recommend having a student do this manually considering the small sample size of this collection. If the harvest was an OAI-PMH endpoint I could look at, I'd likely recommend the opposite.

However, to program for a non-standard API, normalize the metadata for our system (ie. map topics to homosaurus when possible and turn data into edtf), and then do the ingest would be at least 6 hours of work. That could be more depending on how complex of an API they end up making available. If you prefer to go with this route, can do so, but the accuracy of the records would likely be higher having a human normalize the data compared to a rush initial algorithmic way to do so.

Let me know. Thanks!

**Comment by kjrawson** [comment]
This is really helpful, Steven––it's exactly the info I was looking for. And I am happy to have them do it manually. Thanks so much!

**Comment by kjrawson** [comment]
Hey, Steven! I just heard a bit more from them about this collection today and wondered if it changed what you thought of our approach:

Hi K.J.,
I believe there are 914 image records total. Our developer sent the following result from librarycloud. This search shows the 914 records:
 
http://api.lib.harvard.edu/v2/items?q=mc614%20demaios&physicalLocation=Schlesinger
 
Please keep in mind that VIA records in librarycloud are componentized (which I think is what you were looking for), so there is a record for each image, and the record id is a concatenation of via id and urn,  such as:
 
8001253848_urn-3:RAD.SCHL:28255661
 
If needed, here’s more information on LibraryCloud:
http://library.harvard.edu/librarycloud
 
Will this work for you?
If not, please let me know.
Best,
Joanne

**Comment by kjrawson** [comment]
Hey, Steven.
We have another collection that could be a possibility for a batch harvest. The Wellcome Library in London is one of our newest collaborators and they have a collection of almost 500 digitized postcards that we'd like to include on the DTA. [This search](http://search.wellcomelibrary.org/iii/encore/search/C__Sgardiner__Ff%3Afacetlocations%3Aelro%3Aelro%3AOnline%3A%3A__Ff%3Afacetmediatype%3Ak%3Ak%3APictures%3A%3A__Ff%3Afacetcloud%3Afemale%20impersonators%3Afemale%20impersonators%3Afemale%20impersonators%3A%3A__Orightresult__X0?lang=eng&suite=cobalt) should get you to the right page.

I would welcome your thoughts on how much time that would take and whether it's worth it.

Thanks!
K.J.

**Comment by scande3** [comment]
For Harvard, much of it is done, but I have some initial mapping questions:

`notes` (such as: `General note: Title constructed from finding aid folder titles.`)

What should these be mapped to? Or should these be ignored?

`mods:relatedItem`: This seems like it might be collection information I might use during ingest? Or how should this be mapped? An example follows with some values:
```
<mods:relatedItem displayLabel="part of">
<mods:titleInfo>
<mods:title>J. Ari Kane-DeMaios Papers.</mods:title>
</mods:titleInfo>
</mods:relatedItem>
<mods:relatedItem>
<mods:titleInfo>
<mods:title>HOLLIS collection-level record</mods:title>
</mods:titleInfo>
<mods:location>
<mods:url/>
</mods:location>
</mods:relatedItem>
```

I'm actually not an EDTF expert and while I could figure it out, do you know the EDTF syntac for the below date samples?

```
circa 1977
between 1985 and 1989
1980sca.
```

Finally, I do any parsing of their rights, or is it just set to "Contact Host Institution" with additional rights of (from one example):

```
Schlesinger Library on the History of Women in America, Radcliffe Institute: If researchers wish to publish, reproduce, or otherwise make any use of an image in the Schlesinger Library’s collections that requires permission from the copyright holder(s) of the image, it is the researcher’s responsibility to obtain all such permissions.
```

Thanks!

**Comment by scande3** [comment]
@kjrawson - Are you sure on the note and relatedItem? Neither seem to be a summary of the information. Doing that type of mapping will mean the Digital Commonwealth ingest will have to change from relying on Description being about the content of the item to map to "Abstract" and instead mapping that entire field to "Note" there.

**Comment by kjrawson** [comment]
Hey, Steven.
I always appreciate you following up and weighing in with your thoughts.

I spent some more time digging in the XML from [the link](https://api.lib.harvard.edu/v2/items?q=mc614%2520demaios&physicalLocation=Schlesinger) they sent from library cloud and I am not getting hits for searching on some of the metadata that I am seeing on the front end. For example, [this record](http://via.lib.harvard.edu/via/deliver/chunkDisplay?_collection=via&inoID=427555&recordNumber=2&chunkNumber=1&method=view&image=full&startChunkNum=1&endChunkNum=12&totalChunkCount=12&offset=0) and many others, shows an "inscription" that provides additional details on the photo including the inscription on the back. When I do a search in the XML file for "Winnie," as an example, I don't find anything. That's why I was thinking we'd definitely want to preserve that metadata and add it to the Description field. 

The other note you can see on the front end, labeled "general," "Title constructed from finding aid folder titles" I suppose could be added to a "Digital Format" field if it can be parsed out from the other "Note" field information (that is, if we can find that other information). That's not quite how we've defined "Digital Format," but we might be able to expand our usage. 

RelatedItem provides information on what collection each photograph belongs to. I suppose we could put that in "Relation;" though we usually use URLs in that field, it fits there most logically.

I wouldn't expect DC to harvest this collection from us––isn't Harvard a contributor already?

Thanks!

**Comment by scande3** [comment]
Ah, you are right about Digital Commonwealth not ingesting this collection. Metadata consistency is still important to me though. One other option is to support a note field in the DTA data model. Will hopefully have a test ingest ready tomorrow it looks like.

**Comment by kjrawson** [comment]
Thanks, Steven! I appreciate your commitment to metadata consistency! We'll take a look at the test ingest and see what it looks like at that point.

**Comment by scande3** [comment]
@kjrawson - One final issue and then I'll run the test ingest. Where should these records link to? Their feed only provides a full image and a thumbnail url. I'm unsure of how to generate a link to something like: http://via.lib.harvard.edu/via/deliver/chunkDisplay?_collection=via&inoID=427555&recordNumber=2&chunkIndex=0.11_0.11.0&method=view&image=full

An example of their metadata is: https://api.lib.harvard.edu/v2/items?q=mc614%2520demaios&physicalLocation=Schlesinger&limit=250 . Can you inquire on what I might use for the "show url"? Or do I only direct users to the fullsize image? Or is this a case the DTA is ingesting the full size images natively? Thanks!

**Comment by kjrawson** [comment]
Hey, Steven. The DTA is not ingesting the full sized images––all we need are the thumbnails, which can point to their repository. What you just discovered could be a very annoying problem, though––their metadata doesn't include any urls that point to navigable pages on their site, just hosted images. I'll reach out to them and get back to you. My first thought is to link to the full version (though they are a bit slow to load, at least for me), then provide a Related Item link to the collection as a whole. I'll let you know once I hear back from them. Thanks!

**Comment by kjrawson** [comment]
Hi, Steven. At last, I've heard back. Here's there response:
_________
I don’t think they want to be linking back to via, given it’s being retired on Aug 14; if anything they’d want to go to the new hollis images. Can you remind me what they are doing with your data, putting it in an omeka, or some other system? Regarding access to the rest of your collection, do they mean all of Schlesinger images, or just this particular collection? If the latter, they will have all the metadata available in librarycloud, and so would have it all available in your new system. If they DO want to link to hollis, here will be the url syntax:
 
http://id.lib.harvard.edu/images/[IMAGEID]/catalog
 
where [IMAGEID] would be the librarycloud <recordIdentifier> field parsed before the underscore; for instance they would need to parse:
 
8001253848_urn-3:RAD.SCHL:28255661
 
To grab only the id before the underscore:
 
8001253848
 
And so the url to hollis images would be:
http://id.lib.harvard.edu/images/8001253848/catalog
––––––

Is that doable? Thanks!!

**Comment by scande3** [comment]
It is - but from the conversation of via being retired on August 14 has me worried. We are harvesting from VIA... does that mean their API goes away Monday as well so we need to finish our ingest by then?

Otherwise can try an ingest tonight with the destination link specified.

**Comment by kjrawson** [comment]
They had said that it shouldn't affect our work since we're grabbing the metadata from librarycloud.

**Comment by scande3** [comment]
Cool. Will run this tonight. Sorry for a delay on it as got tied up this weekend.

**Comment by scande3** [comment]
@kjrawson -> Just doing some last full record sets locally before the production load. For that, there is one subject I can't map to lcsh: "group portraits". Do you happen to know what LCSH link that references or should that be a subject keyword?

**Comment by kjrawson** [comment]
It's in LCSH in reverse, "Portraits, Group" http://id.loc.gov/authorities/subjects/sh85105203.html 
Does that clarify? Thanks for your work on this, Steven!

**Comment by scande3** [comment]
A few additional ones with that one cleaned up that lack an exact text match in LCSH from errors on a test ingest:

- flowers (plants)
- meals
- banjos
- wedding dresses
- costumes

**Comment by kjrawson** [comment]
Hey, Steven. Here is what I would suggest:

- flowers: http://id.loc.gov/authorities/subjects/sh85049332.html
- meals: this is a tough one, with nothing really close. there's dinners and dining: http://id.loc.gov/authorities/subjects/sh85038076.html
- banjos: http://id.loc.gov/vocabulary/graphicMaterials/tgm000768.html
- wedding dresses: http://id.loc.gov/vocabulary/ethnographicTerms/afset020019.html
- costumes: http://id.loc.gov/vocabulary/graphicMaterials/tgm002610.html

Does it work to use the other thesauri linked through LC, or do they need to be mapped to LCSH? If any of these don't work, I can find other workable terms in LCSH or the Homosaurus. Thanks!

**Comment by scande3** [comment]
It isn't a good idea to do bad mappings of the terms and I don't think the systems handles subjects outside of the LCSH scope well. I can change it perhaps to also parse those vocabularies but likely more effort than it is worth?

I think the main options for ones that don't map to LCSH and that we can't map elsewhere in our model are:

1. Don't parse the term and just skip over those terms.
2. Add them as "Subject--Other" terms since that allows for an uncontrolled vocabulary.

Additionally, a few final terms that I believe to be the last that don't directly meet LCSH:

- guitars
- dressing rooms
- beach grass
- violins

Other stuff:

- One record lacks a date with the identifier: 8001253916_urn-3:RAD.SCHL:28256305 . This one I just thought I'd mention as it seems the other records have dates so this may be a mistake in their metadata.

- It seems homosaurus terms are mostly lowercase while LCSH mostly has the first word capitalized. Should we try to standardize these to be one way or the other in our system?


Thanks!

**Comment by kjrawson** [comment]
Okay, so let's just map the ones that are LCSH, easy, and accurate and skip the others. Here's what I would recommend:

- meals: skip
- banjos: in the singular: http://id.loc.gov/authorities/subjects/sh85011545.html
- wedding dresses: skip
- costumes: in the singular: http://id.loc.gov/authorities/subjects/sh85033238.html
- guitars: in the singular: http://id.loc.gov/authorities/subjects/sh85057803.html
- dressing rooms: http://id.loc.gov/authorities/subjects/sh94005982.html
- beach grass: skip
- violins: in the singular http://id.loc.gov/authorities/subjects/sh85143544.html

Other stuff:
- thanks for mentioning that record. We can take a closer look at it after it's harvested.
-yes, it is true that capitalization for the different vocabularies isn't standardized in our system. Also, when you are browsing the topic facet and you sort by A-Z, there display as two separate lists (e.g., it goes A-Z for one vocabulary, the for the other). But, I would wait on this––some of the other tickets are higher priority. I'll add a ticket for it so that we don't forget.

Thanks!

**Comment by scande3** [comment]
@kjrawson -> Harvard Ingest uploaded to production and works like the Internet Archive ingest of the past. Create (or re-use) an institution and create (or re-use) a collection for the ingest. If you have questions, if it fails to work when you try it, or if there are mapping errors, let me know. Sorry for the long development cycle on this. Thanks!

**Comment by kjrawson** [comment]
Hey, Steven! I ran the ingest earlier today and it pulled in 176 items [https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Fantasia+Fair+Photographs&q=&search_field=all_fields](url). Those records do look correctly mapped, but I need to dig deeper into it tomorrow. It seems like a lot is missing––there should be 933 if the API is correct. Did I close a browser too quickly? I wanted to check with you before trying to run it again. Thanks!

**Comment by scande3** [comment]
Hold off on doing anything with that collection then. The reason for the low number of items is that the system prevents duplicate ingests... which in this case are items with the same "show_url". The instructions from Harvard was to split on the underscore and use that numeric value when creating the show_url. However, that same show_url is then shared by many items.

For example, from https://api.lib.harvard.edu/v2/items?q=mc614%2520demaios&physicalLocation=Schlesinger&limit=10 , the first two items have:

- 8001253847_urn-3:RAD.SCHL:28255505
- 8001253847_urn-3:RAD.SCHL:28255507

These both would create a show_url of http://id.lib.harvard.edu/images/8001253847/catalog based on previous instructions. Why are we ingesting many records that all point to the same catalog record? Is this indeed intentional? Otherwise isn't just one record with a thumbnail accurate for what it links to?

Thanks!

**Comment by kjrawson** [comment]
Hey, Steven.
The way they processed this collection has made quite a mess. They created metadata records for batches of photos––sometimes up to 20. Nikki and I have gone back and forth about whether the DTA should have all 900+ photos or just the 176 unique records. We've decided to settle on the 176 and then have the students enhance the records to make them more accurate and to clearly convey that there are many more images on Harvard's site. Given that, we should be set with this harvest for now. Thank you!
