### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#105]
Hey, Steven!
Our social media accounts have been more active recently, so we were trying to figure out how we might add social media links to the site. Do you think we could add them to the homepage in the footer area? And maybe in the middle of the footer on the internal pages? If we did that, we could cut the Follow Us box that appears on the Contact Us page, I would think. 

As always, I would welcome your thoughts/suggestions. Thanks!

Here are our three accounts:

Facebook: https://www.facebook.com/digitaltransarc/
Twitter: https://twitter.com/digitaltransarc
Instagram: https://www.instagram.com/digitaltransarc/

**Comment by scande3** [comment]
I'll investigate and try to send mockups soon of this.

**Comment by scande3** [comment]
I'll aim to have this completed within the next few days.

**Comment by kjrawson** [comment]
Just wanted to check in on this...have you had a chance to do the mock ups? Thanks!

**Comment by scande3** [comment]
Add in commit df44bfef06b68793d801d50ce8067e984c17588d . Let me know how those work. Thanks!

**Comment by kjrawson** [comment]
These work great, Steven. Thanks!
