### ISSUE TITLE
Collection icon error

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#107]
Hi, Steven.
One minor error cropped up that I can't seem to fix: https://www.digitaltransgenderarchive.net/col/pc289j182

Thanks for your help!

**Comment by scande3** [comment]
This issue should have been resolved. (It was trying to show the image of an audio object and that image then didn't exist). Thanks!

**Comment by kjrawson** [comment]
Perfect. Thank you!
