### ISSUE TITLE
Minor link issue

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#108]
Hey, Steven!
I just added a new contributor, the American Archive of Public Broadcasting, and for some reason the institution URL that I added is being redirected and treated as an internal page: https://www.digitaltransgenderarchive.net/inst/qr46r098n

Thanks!

**Comment by scande3** [comment]
The link was missing the "http" part of the url. Adding that in seems to have fixed the issue. Thanks!

**Comment by kjrawson** [comment]
Sorry about that! Thanks!
