### ISSUE TITLE
Related Sites Linking

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#109]
Hey, Steven.
Hopefully this is a small thing, but when we are linking to external sites from the DTA, is it possible to have them open in a new tab rather than directly navigating there? I am thinking of this page in particular: https://www.digitaltransgenderarchive.net/learn/related. 
Thanks!

**Comment by scande3** [comment]
Go to edit the page, then click on top of the link. Then click the link icon in the editor (the chain in the center of the middle row). In that interface, you should see a tab called "Target". Set that value from <not set> to "New Window (_blank)". Click on "Ok" to save those changes. Repeat that for the other links you want to open in a new tab.

Let me know if this explanation needs further clarification. Thanks!

**Comment by kjrawson** [comment]
Thanks so much for this, Steven––I clearly should have poked around more!
