### ISSUE TITLE
Add "Press Release" to Genre Drop-Down

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#112]
Hey, Steven.
When you get a second, could you add "Press Release" to the Genre drop-down menu? Thanks!

**Comment by scande3** [comment]
This will be pushed up as part of the next release. One note: to be consistent, I'm making it "Press Releases" since other genre categories are plural.

**Comment by kjrawson** [comment]
Thanks, Steven! Any sense of when the next release will be pushed through?

**Comment by kjrawson** [comment]
@scande3 Just checking on when this might be live. Thanks!

**Comment by scande3** [comment]
@kjrawson -> This is complete with the commit fee130a5705485e4701edf69615fe94ca5cd4161

**Comment by kjrawson** [comment]
Wonderful––thank you! @ntantum: when you get a chance, you may want to edit any of the records for press releases that we already have. Thanks!
