### ISSUE TITLE
Adding a timeline to site? {On hold until K.J. makes progress on this}

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#113]
Hey, Steven.
This may be a little ways out, but I'd like to build a timeline using something like [Timeline JS](http://timeline.knightlab.com/). Would it be a lot of work to create a page on the DTA that could display a timeline?
Thanks!

**Comment by scande3** [comment]
Are you asking for just a static page that can implement this for a custom created page of content?

**Comment by kjrawson** [comment]
Yes! It would look something like this: http://kjrawson.net/trans-gender-timeline/.

**Comment by kjrawson** [comment]
Add it to a new page using Source code option.
