### ISSUE TITLE
Batch harvest for Wellcome Library [Higher priority]

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#114]
Hey, Steven.
We have another collection that could be a possibility for a batch harvest. The Wellcome Library in London is one of our newest collaborators and they have a collection of almost 500 digitized postcards that we'd like to include on the DTA. [This search](http://search.wellcomelibrary.org/iii/encore/search/C__Sgardiner__Ff%3Afacetlocations%3Aelro%3Aelro%3AOnline%3A%3A__Ff%3Afacetmediatype%3Ak%3Ak%3APictures%3A%3A__Ff%3Afacetcloud%3Afemale%20impersonators%3Afemale%20impersonators%3Afemale%20impersonators%3A%3A__Orightresult__X0?lang=eng&suite=cobalt) should get you to the right page.

I would welcome your thoughts on how much time that would take and whether it's worth it.

Thanks!
K.J.

**Comment by kjrawson** [comment]
From the folks at the Wellcome: 

"Here is a website with all our API information (at least, the APIs that are ready for public use). I hope this gives your developers what they need in terms of the basics. Let me know what other information you’ll need to access the stuff you want!
 
https://wellcomecollection-iiif.api-docs.io/v1/overview/iiif
 
Cheers,
Christy"

**Comment by scande3** [comment]
K.J.,

This doesn't seem to allow me to actually query the content (ie. the "Content Search API") nor get metadata from the items. That documentation page says "We currently support the Image API." which is just information related to the digital file.

Can you ask them for an example to query for records and obtain their metadata in a machine readable way?

Thanks!

**Comment by kjrawson** [comment]
On it!

**Comment by kjrawson** [comment]
Here's the response I received: 

"Hi K.J.
 
Ah, sorry I got the wrong end of what you’re trying to do at the moment. Once you have the finding aid, you should be able to harvest the MARC records using z39.50 (the finding aid will need to include the system number for Sierra, the b – number). I’ll leave that in Alexandra’s hands!
 
Once you’re ready to download the images and image information, you can get that via the IIIF API I linked to below, again using the b-numbers to target the items you need.
 
Cheers,
Christy"

––––––––––––––––––––––––––––––––––––––––

Does this make sense to you, Steven? Alexandra is an archivist there who is working on pulling together the finding aids that we'll be including on the DTA. These seemed like separate projects to me, but Christy sees them as interdependent. I wanted to get your take before I responded.

Thanks!

**Comment by kjrawson** [comment]
Here's some additional info from Alexandra: "The b number is given at the bottom of the record page and in the URL e.g. https://search.wellcomelibrary.org/iii/encore/record/C__Rb2921429"  

Does that provide any clarification, Steven? I am guessing not...

**Comment by scande3** [comment]
I'm still unsure as to how I get the list of records to ingest. Are those supposed to come from the Finding Aid? So the ids from the finding aid is what we would query?

(Z39.50 isn't a harvest standard btw... but it does allow one to query a catalog system to get some metadata. I have written code in the past to query one and can look into how that worked this weekend to refresh my memory).

**Comment by kjrawson** [comment]
It seems that we'll need to work with Alexandra to develop a finding aid that includes the ID's, then. We can get working on that soon. Thanks!

**Comment by ntantum** [comment]
Hi Steven!
One of our Team Leaders in the lab, Carlito, went ahead and pulled all the identifiers for the Wellcome collection items. You can access the spreadsheet here: [https://docs.google.com/spreadsheets/d/1wq6nDt6b3sDY3N-cYBYj-tn8RYEpUTHFAPp9JkoPpyQ/edit#gid=0](https://docs.google.com/spreadsheets/d/1wq6nDt6b3sDY3N-cYBYj-tn8RYEpUTHFAPp9JkoPpyQ/edit#gid=0)

Let us know if there's anything else you need for this batch harvest!

**Comment by scande3** [comment]
@ntantum -> It appears that the google spreadsheet linked above has been deleted?

**Comment by ntantum** [comment]
Hi Steven!

I've attached the spreadsheet. Let me know if you have any questions!

[Wellcome Identifiers.xlsx](https://github.com/CollegeOfTheHolyCross/dta_sufia/files/1656220/Wellcome.Identifiers.xlsx)

**Comment by scande3** [comment]
Wellcome ingest should be complete.

**Comment by ntantum** [comment]
The ingest looks great! Thanks, Steven!
