### ISSUE TITLE
Batch harvest for UT San Antonio [Lower priority]

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#115]
Once you get a sense of how long it takes you to script for these batch harvests, could you let me know how long it might take you for this collection? 

http://digital.utsa.edu/cdm/search/collection/p15125coll9/searchterm/lopez%20and%20cardona!box%201%2C%20folder%201!lopez%20and%20cardona/field/all!source!all/mode/all!exact!all/conn/and!or!and/order/nosort/ad/asc

There's no huge rush on this one since the materials are later and less unique.

**Comment by kjrawson** [comment]
Here's the response from UTSA:
"All of our CONTENTdm collections are open for OAI harvesting, Amy has set this up for us.  Our Dublin Core metadata is able to be harvested as XML.
 
I’m not sure what harvesting tool KJ is using, but he should be able to synch with the metadata and the compound objects from the Manuscripts in Bulk collection that Lopez and Cardona is uploaded to.
 
Here’s some info on OAI: http://www.openarchives.org/
 
Julianna"

Let me know if you need additional info!

**Comment by scande3** [comment]
They are not very helpful. Knowing it is contentDM, I was able to figure the needed urls. Sample for myself for later reference:

OAI endpoint of: http://digital.utsa.edu/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc

Record Info: http://digital.utsa.edu/utils/ajaxhelper/?CISOROOT=p15125coll9&CISOPTR=41088

Record Image: http://digital.utsa.edu/utils/getprintimage/collection/p15125coll9/id/41088/scale/100/width/1024/height/691/rotate/0/filename/image_file.jpg

**Comment by kjrawson** [comment]
Do you need me to get additional info from them? Sorry they weren't terribly helpful.

**Comment by scande3** [comment]
No additional information needed at the moment. Hope to run a test ingest tomorrow and push up other changes.

**Comment by scande3** [comment]
Attached is a sceenshot of a sample item for this ingest. It's metadata can be viewed at: http://digital.utsa.edu/oai/oai.php?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:digital.utsa.edu:p15125coll9/41041 . Are there any adjustments I should to this? Thanks!

![screenshot from 2017-10-16 17-39-51](https://user-images.githubusercontent.com/786466/31636651-58eefaa6-b299-11e7-9dbd-b01d6073e8cf.png)

**Comment by scande3** [comment]
San Antonio ingest with commit: c2fc991210a3102af0b40172d829b8e85824665c

Of note, I fixed the date from the above screenshot to only be a year. Additionally, I changed the Rights to make the link a url and end it with "copyright" over "rights" for the sentence.

If that would all be correct, feel free to run it. If there are changes, can make those tonight. Thanks!

**Comment by kjrawson** [comment]
Hey, Steven. Thanks for this! Nikki and I just looked it over together and we just had one question: the Institution should be University of Texas, San Antonio (rather than "harvard books"--not sure where that's from). Otherwise, it looks great! And your two changes on date and rights are helpful.

**Comment by scande3** [comment]
The weird name is because I chose to ingest it into that institution locally. You can choose what institution and collection to put the upload into and the functionality is already on the server?

**Comment by kjrawson** [comment]
Hey, Steven! I ran the ingest last night and it appears to have successfully ingested 243 items out of the 283 in the search results. Do you think this is another case of not ingesting duplicates? I haven't yet investigated what might be missing, but I'll try to take a look later today. Thanks!

**Comment by kjrawson** [comment]
Okay, I think I figured it out. If you look at the [view all files](https://www.digitaltransgenderarchive.net/dashboard/files) display from the back end, you can see that some don't appear to have a collection that they are associated with. When I've gone in and edited those and resaved them, it then adds it to the collection. My guess is that they were missing some sort of metadata (Creator?) or that there was some other glitch in saving them. I expect that once the students brush up the metadata the collection will have all of the items.

**Comment by kjrawson** [comment]
This collection is now fully processed and is up on the site. Thanks, Steven!
