### ISSUE TITLE
Generating Thumbnails

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta_sufia#117]
Hi Steven!

I am the new project coordinator for the DTA. It's nice to (kind of) officially meet you! We are having some issues with thumbnails, specifically in the Chi Chapter Tribune collection that we added today. No thumbnail is coming up at all and our attempts to regenerate them do not seem to be working. We had this issue earlier today on a different file but the thumbnail finally generated about 4 hours later. Is there a reason why this might be running so slowly? 

Thanks in advance!

**Comment by scande3** [comment]
Hiya! From what I can see, it is because the PDF is malformed according to the code library I use to parse text from it. I don't know if you have the ability to correct it or can let me know the identifier for the object?

For now, I have the code ignore the error, but some/all of the OCR text search for that item will not work. Let me know if you still cannot generate the tumbnail.

**Comment by ntantum** [comment]
The thumbnails are working now! I am not sure how to change the PDF itself so that it is correctly formed, but the identifiers for the objects we have up so far (that also gave us trouble) are 0c483j51k, db78tc192, 0z708w62d, sj139217j, and 5x21tf626. However, we are still adding to this collection and I have a feeling all the PDFs will be malformed since they all came from the same place. Let me know if there is something I can do to correct the PDFs on our end before uploading them.

**Comment by scande3** [comment]
I did an update that will make things slower when initially hitting "Create" on a new object. It essentially runs a second batch of checks to try to ensure this process does kick off. Can you let me know if you notice thumbnails still not generating or if you notice any problems with uploads in the near future? Have K.J. text me or give you me cell to text if this update broke anything. Thanks!

**Comment by ntantum** [comment]
Great, thanks! I will let you know if anything is amiss when me or the students are uploading items today. KJ gave me your number just in case!

**Comment by scande3** [comment]
How has it been after 7 days of this brute force change? Still not generating thumbnails?

**Comment by ntantum** [comment]
The thumbnails are definitely generating! This problem is fixed!

**Comment by ntantum** [comment]
Unfortunately, this problem has come back. Now, zero thumbnails are generating for any of the objects processed yesterday! We have tried regenerating them but that has not worked either.

**Comment by scande3** [comment]
The background jobs were not running on the server for some reason.  Potentially do to some error on the physical server stopping them? Assuming you have superuser permissions like K.J., you should be able to access the following: https://www.digitaltransgenderarchive.net/admin/actions

The "Restart Background Scripts" are one command you can try. I've run that and it seems the background jobs (like Thumbnail creation) are running again. Let me know if there are items that it failed to generate thumbnails for. Thanks!

**Comment by ntantum** [comment]
Awesome, thank you for that link! It should be helpful in case something like this happens again. The thumbnails are all back up!
