### ISSUE TITLE
Minor change in record display

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#119]
Hey, Steven!
Could you change the text display where it says "People/Organizations" in the records to instead say "Subject(s)", as it does for faceting? The format for Topic is "Topic(s)", so that would be good to replicate: "Subject(s)"
Thank you!

**Comment by scande3** [comment]
Complete with commit e32451b81b6528c6dadd09cf7bbfc770b426e68f

**Comment by kjrawson** [comment]
Perfect––thanks so much!!
