### ISSUE TITLE
Creator and contributor type-ahead

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#12]
Would it be possible for the creator and contributor fields to have type-ahead fields with the previously entered terms (similar to Subject Coverage--Other)?

**Comment by scande3** [comment]
Potentially added 14bdaf842414e2cdd6ff705b87dc2c0757540272 and 00f8cca1f36d8d2deab11a571170acab83f6a156 . Better matching as well where an exact word match anywhere in a string will return results (like "Betty" for Creator).

White space at the end of these items has been removed and will be removed upon submission in the future.

Can you give examples of any terms that give problems? Thanks!

**Comment by kjrawson** [comment]
Fantastic! Thanks so much for this. I'll reopen if there are any problems with this.
