### ISSUE TITLE
Items losing collection metadata

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta_sufia#120]
Hi Stephen - 

It was nice talking to you earlier today! I apologize for already having another issue. One of our Team Leaders brought our attention to another problem after we got off the phone today.

After processing an item, some items have been losing their collection metadata. The collection, of course, is a required field. Although the students have been choosing the collection information, the item will later lose its' collection information, allowing it to basically float freely in the site without an attachment to a collection.

We have dealt with this before when making whole collections public as well.

For a specific example: The Billie Ert Obituary (https://www.digitaltransgenderarchive.net/files/2v23vt59c). They processed the item with a collection but, when it saved, it deleted the collection information. When Katie (our team leader) went in to fix it, it saved the correct collection but also kept the original collection-less item. Therefore, there was an item attached to the Newspaper collection and then a duplicate item with no collection. I have since deleted the duplicates, but I thought it would be important for you to know these were being generated too!

I hope this is clear, let me know if you have any questions!

**Comment by scande3** [comment]
Just to verify on the duplicated item case: this occurred when using the "edit" link on the item's page and setting the collection there? Or was some other process used that caused this?

**Comment by ntantum** [comment]
Hi Stephen - just wanted to let you know that the students have been reporting more duplication issues. It seems they have found some items have been duplicated but have been automatically posting as open access with all the correct metadata (in opposition to other duplicates which are private but with zero metadata).

**Comment by scande3** [comment]
The next time this happens, can you link me to the original and the duplicate rather than correcting it? Just one example should be fine and would allow me to then try to look at the data to see how it might have occurred. Let me know if feasible. Thanks!

**Comment by scande3** [comment]
(I'll also try to push up something tomorrow night designed to try to throw an error in the case a duplicate seems like it is about to be created).

**Comment by ntantum** [comment]
I can definitely do that! The students are currently on Fall Break so they will not be uploading items until next week, but I will tell them to leave any errors be and I will link you to the item! Thanks!

**Comment by ntantum** [comment]
Items seem to be losing metadata information somewhat frequently this week! Here is an example of one that we have not fixed

Title: Kenneth Marlowe (1)
[https://www.digitaltransgenderarchive.net/files/8s45q916b](https://www.digitaltransgenderarchive.net/files/8s45q916b)

On that view, it says it is in a collection but when you click to edit it, it should show the collection metadata as empty.

**Comment by ntantum** [comment]
I have another example of an item that duplicated, as I mentioned in the original post.

This item posted correctly with all metadata:
[https://www.digitaltransgenderarchive.net/files/xp68kg44x](https://www.digitaltransgenderarchive.net/files/xp68kg44x)

It automatically duplicated but without the collection metadata here:
[https://www.digitaltransgenderarchive.net/files/t435gd221](https://www.digitaltransgenderarchive.net/files/t435gd221)

**Comment by scande3** [comment]
@ntantum -> Thanks! Will debug these by Saturday and remove the extra duplicate when complete.

**Comment by scande3** [comment]
@ntantum -> Actually, I'll let you clean up the two cases above (ie. adding in the collection and deleting the duplicate).

The following was changed in commit 654b3d4c79d422f651072ac71d35d4dd5526c82e to see if it affects the issue:

- Refactored the upload code slightly to remove more of Sufia's default behavior.
- Disabled the submit button one an upload button is clicked. From what I can tell, one of those items was created 30 seconds prior to the other item. My best guess at the moment is that the duplicate was caused by clicking "Submit" more than once which would create two objects.

Let me know if you still experience issues or see anything new from these changes. Thanks!

**Comment by ntantum** [comment]
There have been no more duplicates! Thank you!
