### ISSUE TITLE
Missing Collection

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta_sufia#123]
Another small problem: we have a collection titled "University of Maine Finding Aids" that we published last week. For some reason, this collection is not showing up on the collection listing page ([https://www.digitaltransgenderarchive.net/col](https://www.digitaltransgenderarchive.net/col)).

However, if you go to University of Maine's page ([https://www.digitaltransgenderarchive.net/catalog?f%5Binstitution_name_ssim%5D%5B%5D=LGBTQ%2B+Collection%2C+University+of+Southern+Maine+Libraries](https://www.digitaltransgenderarchive.net/catalog?f%5Binstitution_name_ssim%5D%5B%5D=LGBTQ%2B+Collection%2C+University+of+Southern+Maine+Libraries)) , you can see it listed as a collection on the left.

Not an urgent problem, but I have played around on the back end and haven't been able to figure it out!

Thanks in advance!

**Comment by ntantum** [comment]
The same thing seems to be happening with the Tretter Transgender Oral History Collection.

[https://www.digitaltransgenderarchive.net/collections/7s75dc53m](https://www.digitaltransgenderarchive.net/collections/7s75dc53m)

**Comment by scande3** [comment]
There was a configuration setting I had missed that resulted in only 100 collections being returned on that page (the default value). I've fixed this and those should now all be showing up. Thanks!

**Comment by ntantum** [comment]
They are all there! Thank you for the quick fix!
