### ISSUE TITLE
Homosaurus Terms in Metadata

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta_sufia#124]
Hello!

We are having a weird bounce back issue with certain Homosaurus terms. For example, our team leader, Katie, was having trouble adding the terms "women's organizations" and "women's music festivals" from the homosaurus to this item: [Topher Gross Oral History](https://www.digitaltransgenderarchive.net/files/jw827b940) . Clicking the term does not add it to the metadata like usual. Instead, it bounces back (hard to explain completely, but hopefully you will see when you try to add the term).

I also wanted to let you know that the LCSH terms are sometimes adding as links instead of just the subject term. When we go back in to edit the object, the term we are looking at will have disappeared from the metadata completely. Sometimes we can fix it right away but other times we have had to wait a couple days until it will accept the term normally. Since we have been able to fix all of them within a couple days so far, I do not have any current examples (and it is not a major issue right now anyway) but I wanted to put it on your radar in case I have any concrete issues in the future!

Thank you!

**Comment by scande3** [comment]
@ntantum -> The Homosaurus terms you mentioned should work now as the code now properly handles terms that have a single quote.

For LCSH, I'd need more information as to the exact entry terms and behavior being experienced (or being linked to it as it occurs). The system actually only stored the LCSH URI in the record and not the string value as that can change over time. So I'd need more information to know at what point that lookup might be failing.

Thanks!

**Comment by kjrawson** [comment]
@ntantum is this still an issue?

**Comment by ntantum** [comment]
The students have not reported this as an issue since 2.0 was updated. Thanks!
