### ISSUE TITLE
One Missing Item

### ISSUE THREAD

**Issue by ntantum** [CollegeOfTheHolyCross/dta_sufia#125]
Hi Steven!

Is there anyway you would be able to find any items with missing collection metadata? K.J. and I keep a list of all the collections and the number of items in each collection.... but our grand total of items is reading at 4,488 while the website is saying 4,489. I have checked our math many times but I fear the missing item is floating collection-less in the abyss.

Thanks!

**Comment by scande3** [comment]
The following object ids have collection data that doesn't seem persisted:

"2801pg33n", "nc580m69p", "d217qp54p", "x920fw95x", "br86b364d", "0v8380591", "xs55mc14f", "dz010q25p", "02870w10j"

You can access the item by doing: https://www.digitaltransgenderarchive.net/files/<id> (where <id> is one of the values above). Note that these show a collection in the display: the value is in Solr but not persisted elsewhere. I can write a script to fix this if desired over manual correction - let me know.

I'm unsure if these are from a previous issue or not (ie. how recent these objects are) or if it catches the one you are missing. The new system will correct this issue in the future. Let me know if I can assist further or if the one you were looking for isn't among these.

Thanks!

**Comment by ntantum** [comment]
Woohoo, one of those items was the mystery item! Thanks for the help!
