### ISSUE TITLE
Title sort

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#127]
Hi, Steven.
Sorting search results by title doesn't seem to be working––it appears to just use date and sort oldest to newest. Thanks!

**Comment by scande3** [comment]
@kjrawson -> Title sort should now be working correctly. Future tickets should likely be against the new codebase at https://github.com/CollegeOfTheHolyCross/dta/issues btw. Thanks!

**Comment by kjrawson** [comment]
Sorry about that! Would you like me to transfer over any remaining tickets?
