### ISSUE TITLE
Subject-Term––Other not consistently showing existing terms

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#14]

**Comment by scande3** [comment]
Do you have an example of this? Or is the behavior random?

**Comment by kjrawson** [comment]
Here are a few examples:
American Psychological Association
International Foundation for Gender Education

**Comment by scande3** [comment]
Should be fixed in next update.

**Comment by scande3** [comment]
This should be fixed the following commit: c590082d25592bf587a1228201aa959b0ff87848

However, this should still be left open as the form should remove any end spacing on a string when submitting. For example, "International Foundation for Gender Education" has one record with a space at the end.

**Comment by kjrawson** [comment]
This doesn't seem to be fixed––while the type-ahead is working, the counts are often 0. Not a major concern, though.

**Comment by scande3** [comment]
Potentially fixed as 14bdaf842414e2cdd6ff705b87dc2c0757540272 and 00f8cca1f36d8d2deab11a571170acab83f6a156 . Better matching as well where an exact word match anywhere in a string will return results (like "Outreach").

White space at the end of subject--other has been removed and will be removed upon submission in the future.

Can you give examples of any terms still giving problems? Thanks!

**Comment by kjrawson** [comment]
Oh, this is great! I hadn't thought about doing matching anywhere in a string––that will be really helpful. We can close this for now, and if any other issues come back up I'll reopen it. Thank you!!!
