### ISSUE TITLE
Harvest Internet Archive (high priority)

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#21]
https://archive.org/details/digitaltransgenderarchive

**Comment by scande3** [comment]
Notes from test ingest:

- https://www.digitaltransgenderarchive.net/files/m039k492n -> Metadata from http://archive.org/download/transgendertapes1042unse/transgendertapes1042unse_meta.xml

- https://www.digitaltransgenderarchive.net/files/wd375w317 -> Metadata from http://archive.org/download/enfemmecomics02unse/enfemmecomics02unse_meta.xml

- https://www.digitaltransgenderarchive.net/files/n870zq86p -> Metadata from http://archive.org/download/enfemmefictionma13unse/enfemmefictionma13unse_meta.xml


So there are some questions like:

- How should volume be concatenated?

- For required fields that don't exist in that metadata like Creator, what would be used then?

- What might be missing from my attempt at a mapping?

**Comment by scande3** [comment]
- Date is missing in mapping.

- Creator and publisher the same for default? A. Leave blank and will add that.

- type and genre no default? A. Will enter manually.

- No default collection sort needed for now.

- Should be all Homosaurus subjects, Should catch / log if not.

**Comment by scande3** [comment]
Code updates and set to ingest 5 items (I deleted the previous three test items). Assuming this seems to be good, would then increase it to do all the items in Internet Archive. Of note:

- Date should now be added.

- OCR text from IA is searchable in the site search.

**Comment by kjrawson** [comment]
I just ingested the 5 items and they look good to me. Thanks for making those changes! Let me know when you reset the limit and we can delete the test items and ingest the entire collection.

**Comment by scande3** [comment]
Updated to pull the entire collection. You don't need to delete the existing items (it shouldn't duplicate them - if it does, it is a bug).

**Comment by kjrawson** [comment]
Perhaps it's still going, but there are now 10 items that were harvested.

**Comment by scande3** [comment]
Looking into it.

**Comment by scande3** [comment]
After some quick debugging, it appears the server doesn't correctly download the zip file of all the images correctly to make the thumbnail from. Not sure why. I added code to retry the download up to three times and seems to be chugging along now...

**Comment by scande3** [comment]
Or perhaps still an issue. Will look at it shortly again.
