### ISSUE TITLE
Deleting user roles gives an error

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#26]
When I've tried to delete a few users (students who are no longer in the lab), there's an error and it seems as though they aren't deleted.

**Comment by scande3** [comment]
This should be fixed (in theory) in the following commit: c590082d25592bf587a1228201aa959b0ff87848

Please test to verify.

**Comment by kjrawson** [comment]
Just tried it again, but I got the same error:
![roleserror](https://cloud.githubusercontent.com/assets/15388345/12553943/18f204da-c348-11e5-8748-6d428235d247.jpg)

**Comment by scande3** [comment]
Updated if you could try it again? (Commit 66f89f9144ff15c6a6dc5a5de53588f5958e8801).

**Comment by kjrawson** [comment]
Works perfectly. Thanks!
