### ISSUE TITLE
Default search results not including titles

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#27]
It appears that doing a search for "all text" isn't searching the titles of objects. I searched for "AEGIS News" and the results were only from subject terms. If you repeat the search with limiting to title, the results are more what you'd expect with the full collection of those newsletters.

**Comment by scande3** [comment]
This should have been added now in commit 10a0e4e864d83d6d11d219b7e77af8e06c3f22fe .

(The bug was because the title is to be the preferred search field over any other matching text but had that configured wrong).

**Comment by kjrawson** [comment]
All set. Thanks!
