### ISSUE TITLE
Detailed faceting in Collections view has error

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#28]
If you view AEGIS News as a collection, then select "more People/Organizations" in the metadata fields, you'll get the error that I've done a screenshot of here.

<img width="1280" alt="screen shot 2016-01-26 at 4 23 15 pm" src="https://cloud.githubusercontent.com/assets/15388345/12595666/97b9773c-c44a-11e5-95b6-cbbf80cb395a.png">

**Comment by scande3** [comment]
Should be fixed as of commit ba775c37dc55abe13fd7f99db31ed40df5b2a998

**Comment by kjrawson** [comment]
Perfect. Thanks!
