### ISSUE TITLE
Default sort "My Files" by Recently Uploaded

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#29]
In the admin interface throughout the fall, the default display for the "My Files" list was recently added. This was helpful because I could check the files as students uploaded them. If it's possible to add that as a display option, that would be great!

**Comment by scande3** [comment]
This should have been added now in commit 10a0e4e864d83d6d11d219b7e77af8e06c3f22fe .

Question: Should a "date uploaded" sort be available in the public interface as well? Or might that be too confusing?

**Comment by kjrawson** [comment]
That works perfectly––thanks!

And to answer your question: I don't think the date uploaded field is necessary in the public interface. Though, I suppose it might be interesting to make "recently added" a browse option. What do you think? Either way, it's a lower priority for me.
