### ISSUE TITLE
Help text edits

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#3]
*one new bullet point from the MAP should be added to the input guidelines in "Title" and "Alternative Title" ("For serials with changing titles...")
*need to add help text from the MAP for: Type, Genre, Analog Format, Digital Format, Relation

**Comment by kjrawson** [comment]
Here's a new MAP with a few changes to Creator and Contributor, for when you have a chance to make these edits. Thanks!
[DTAMAP2-4.pdf](https://github.com/CollegeOfTheHolyCross/dta_sufia/files/194251/DTAMAP2-4.pdf)

**Comment by kjrawson** [comment]
Here's the latest one: 
[DTAMAP2-5.pdf](https://github.com/CollegeOfTheHolyCross/dta_sufia/files/323819/DTAMAP2-5.pdf)

**Comment by scande3** [comment]
These should all have been made. Let me know if I missed anything!

**Comment by kjrawson** [comment]
You fixed them all––thanks!!
