### ISSUE TITLE
Enable users to exclude Finding Aids in searches––Help text

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#31]
All of the finding aids included in the database are all clearly marked as "Finding Aids" in their metadata. As the database grows, it would be helpful for users to be able to exclude these from their searches so that their results only include historical objects (maybe a checkbox with a help text popup?). As you may remember, we won't be sending those records along to DC or DPLA either, in case that has any impact on how you set this up. I am also wondering if it might make sense to be able to only search finding aids...

**Comment by scande3** [comment]
An alpha version of this was added. A help icon with a quick popup can replace the current text question mark if the uploaded solution is what you are looking for. I won't give more details so that you can try it as a user might. This was added in commit 3c71454265eb13806e700061928bf45376589b35 .

**Comment by kjrawson** [comment]
Help text for finding aid exclusion: 

"Check this box to limit your search results to digital or digitized historical materials. Finding aids are documents that describe collections held in archives and they may not be relevant for all researchers."

**Comment by scande3** [comment]
Added that help text to commit 015ba37ac2b68450e46eec5752e34b8531553b7e . Let me know how it works!

**Comment by kjrawson** [comment]
Perfect––thanks!
