### ISSUE TITLE
Roles for accessing records

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#32]
One of the student groups uploaded a Vanguard file, https://www.digitaltransgenderarchive.net/files/gf06g2664, and though I can see it fine when logged in, they get an error trying to review it. I've attached the error so you can see it.

![img_3193](https://cloud.githubusercontent.com/assets/15388345/12659888/0cc375c4-c5df-11e5-88c9-bb506f503e63.JPG)

**Comment by scande3** [comment]
Is this occurring for all "flagged" items? (I'm assuming this is a flagged item by the error message)?

**Comment by kjrawson** [comment]
Yes, this is a flagged item. I can check with them to see about this.

**Comment by scande3** [comment]
I did a very quick fix on this as commit 07294b336ba255486e6a7b814c64b6f17d46b3f8

Also notice that you can access the item show page when not logged in (despite it not being set to visible). Not showing in any search results so the question is: should I fix so the show page returns an error when not logged in? Or leave it as is since it might be useful to show others before posting something that don't have an account (and no one from the public would know the random ID to access it)?

Thanks!

**Comment by kjrawson** [comment]
I checked with the students and they didn't have trouble with any other items, but there weren't many that were explicit. I had to give an additional student admin privileges yesterday because they weren't able to see other records that had been processed but not yet visible (they work on different parts of a collection at the same time and wanted to see the records for items that had been very recently uploaded to standardize metadata). 

To answer your question: it probably makes sense to leave it as is since there's such a low probability that anyone would stumble across it. It seems like that's what you would suggest, too?

**Comment by kjrawson** [comment]
I just had the occasion to test out this functionality (sending a link to an object that isn't fully "public" to get feedback from a collaborator). When I navigate to a private object in an incognito window, the thumbnail doesn't display: https://www.digitaltransgenderarchive.net/files/x346d418q. Does that happen for you, too?

**Comment by scande3** [comment]
Added a temporary fix for this use case but we should likely discuss it more. Should I remove the restriction only on thumbnails? Or also remove an authorization check on the full file download?Or  Should "private" restrict viewing to authorized users, "Institution Name" to it being accessible but not showing in a search, and "public" for searchable and accessible?

Perhaps we should do a call sometime next week to discuss this and the institution/collection ticket?

Thanks!

**Comment by kjrawson** [comment]
No longer relevant as we added a third state
