### ISSUE TITLE
Multiple institutions contributing to a collection

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#33]
This is more of an error in how I've conceived of the repository and created the MAP, but I thought you might be able to help me think through it.

Here's the issue: we have some collections that could include materials from multiple institutions. It's easy enough to add multiple institutions to the collection on the create collection page, but then there's no way of indicating which materials are from which institution. That seems like a problem for a few reasons: researchers won't know where to go to find things and we aren't giving proper credit for the digitization work when we lump multiple institutions together.

For now, we created a separate collection and added the name of the institution to the collection title (see Fantasia Fair: Program Guide). But, I am thinking of that as a temporary fix.

Any ideas?

**Comment by scande3** [comment]
Initial support added for this to try out. Of note:

- All existing objects have been assigned to the first institution a collection belongs to.

- You can now edit an institution / collection on an item's edit page. Please do not change the collection elsewhere at this time.

Let me know how that seems to work thus far. Thanks!

**Comment by kjrawson** [comment]
I am testing this out now. Two files I removed from a collection––Cape Air and Evelyn Shade Promotional Flyer––can't be edited, probably because they don't have a collection affiliation. I'll check out some of the others now.

**Comment by kjrawson** [comment]
Otherwise working great!

**Comment by scande3** [comment]
Can you try to edit those two that didn't have a collection?

This should have been added in commits 65fe78f0f2a8c3866864e4a25be5ec00ed944fb8 and a1856e966e78dd1a8b733488c8d201db34412adc

**Comment by kjrawson** [comment]
Yes, both of those are all set. Thank you!
