### ISSUE TITLE
Default New Collection set to invisible (low priority)

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#34]
Could you make the default setting for newly created collections to be invisible? I realized that the collection list is displaying collections that we may take a few weeks to work on before the collections as a whole become visible. Thanks!

**Comment by scande3** [comment]
This may be done as part of the visibility swapping update. (They default now seems to be private but unsure what affect that will have... just a note in case you create a new collection and it doesn't work elsewhere in the admin to let me know).

**Comment by kjrawson** [comment]
Will do. Thanks!
