### ISSUE TITLE
Label for "People/Organizations" changed to "Subject"

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#36]
Could you change the label for the "People/Organizations" facet to "Subject"? Though we realize that's very close to "Topic," in practice, the "Subject Coverage––Other" field is used for other proper nouns beyond people and organizations. The distinction between topic and subject seems clear enough in practice when the two facets are right next to each other. Thanks!

**Comment by scande3** [comment]
Should be complete with commit of ba775c37dc55abe13fd7f99db31ed40df5b2a998

**Comment by kjrawson** [comment]
Thanks!
