### ISSUE TITLE
Centering Logos on Browse by Institution page

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#38]
Do you think it might look better to center the logos in the spaces allotted in the lefthand column? The square ones look fine, but many of them are similar to the proportions of a bumper sticker, so there's extra space below them. Just a thought.

Could "The" be taken out of the alphabetical sort so that "The University of Texas at San Antonio" comes after "Transgender Archives"? 

Thanks!

**Comment by scande3** [comment]
This should be done so feel free to test and let me know if it should be different. Commit 130f840d72ff37b0e6c7199384d69be2dfd2ca76

**Comment by kjrawson** [comment]
The alphabetizing looks great––thanks! Could you try centering the logos? Thank you!
