### ISSUE TITLE
Collection page––remove "the" from alpbebetizing

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#39]
Could you take out "the" at the start of titles when they are being sorted alphabetically on the Browse>Collections page? Thanks!

**Comment by scande3** [comment]
This should be done so feel free to test and let me know if it should be different. Commit 130f840d72ff37b0e6c7199384d69be2dfd2ca76

**Comment by kjrawson** [comment]
Perfect. Thank you!
