### ISSUE TITLE
Ability to make Collection invisible

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#43]
There's another open ticket for setting the default Collection visibility to private when a collection is created, but it would be helpful if it were also possible to set a whole collection to private after it's been created. I received our first copyright complaint (I finally got ahold of someone who co-owns an object that we had the rights from the other person to post) and I think they will come around to letting us keep it up, but I wanted to set the collection to invisible (rather than deleting it) while we work it out.
Thanks!

**Comment by scande3** [comment]
Will add this functionality tonight. I assume you want it to make all of the child objects private when a collection is set to private too?

**Comment by kjrawson** [comment]
Yes, that would be great. Thanks, Steven!

**Comment by scande3** [comment]
Functionality added as buttons on the collection that may need to be adjusted yet. Hopefully this works until they can be positioned better. Let me know if you have questions.

This should have been added in commits 65fe78f0f2a8c3866864e4a25be5ec00ed944fb8 and a1856e966e78dd1a8b733488c8d201db34412adc

**Comment by kjrawson** [comment]
I set Drag Queens of Toronto to invisible, but it seems to still be showing up in the collections list even when i am logged out. I wonder if it needs to be reindexed when we change the visibility?

**Comment by kjrawson** [comment]
Even after a reindex, it is still visible...

**Comment by scande3** [comment]
This should have been fixed.

**Comment by kjrawson** [comment]
All set. Thanks!
