### ISSUE TITLE
Adding additional statement under rights

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#44]
Would it be possible to add the following statement to be included under the Rights statement in each record?

"For more information on copyright, please read our policies [hyperlinked]." 

After the copyright issue I have been dealing with over the past few days, I am thinking that a clearer path to the policies would be helpful.

Thank you!

**Comment by scande3** [comment]
This should have been added in commits 65fe78f0f2a8c3866864e4a25be5ec00ed944fb8 and a1856e966e78dd1a8b733488c8d201db34412adc

**Comment by kjrawson** [comment]
That's perfect––thanks!
