### ISSUE TITLE
Additional Browse options?

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#45]
Hi, Steven!
I've heard from folks that they would like additional "ways in" to the materials in the collection. I don't think they know that they can enter a blank search to see the full collection and just narrow down from there. I wonder if we might add another browse option for genre, now that we have a wider range of materials? Subject or Topic would be other options, but genre seems most useful to me. Do you have any thoughts on this?
Thanks!

**Comment by kjrawson** [comment]
Another idea for browsing would be "recently added"

**Comment by scande3** [comment]
Browsing by topic, genre, and latest added are now available. There is some slight adjustment to be done but let me know what you think and what might need to change about them. This is commit 02fcbcea0d6c5d02b5fe0d5a935909452a3643db .

**Comment by kjrawson** [comment]
Awesome! Looks great! I didn't see anything that needed to be changed.
