### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#49]
Hey, Steven.
A lot of error messages have been popping up the last few days. Often, they come up when editing a record or a collection, though often the changes are saved. Also getting an error when trying to change the visibility of some objects (Reed Erickson in boots). I've attached one error screen, though the students grabbed at least one other screenshot earlier today as well. 

![seconderror](https://cloud.githubusercontent.com/assets/15388345/13271882/10e78866-da66-11e5-859e-c6edc0b945bf.jpg)

**Comment by kjrawson** [comment]
![error](https://cloud.githubusercontent.com/assets/15388345/13271896/1feae588-da66-11e5-983c-d4a01abd7106.jpg)

**Comment by kjrawson** [comment]
![thirderror](https://cloud.githubusercontent.com/assets/15388345/13271996/e8fb034a-da66-11e5-8cff-5095b770d36a.jpg)

**Comment by scande3** [comment]
K.J.,

Could you better describe the first two errors? I tried changing the visibility of the "ONE Archives at the USC Libraries" to public and then changed everything to private without error. Are you getting that error somewhere else then clicking the "Make All Visible" link?

Additionally, for the third error, is there a specific way to duplicate that? From what I can tell, a student tried to update an item without a collection selected?

**Comment by kjrawson** [comment]
All three errors here were mine. One error happened when I tried to make the Reed Erickson collection public (so it was happening at the collection level, not the institution level). The other errors happened when I was trying to change the visibility of single objects ("Reed Erickson in boots" was one, for which I've had to add the collection info to a few times––it seems to take it off when the error occurs in trying to make it visible). Another example was when I was trying to edit a LCSH in "Reed Erickson with family" and received the error when attempting to save (it seems to have preserved the changes, despite the error message). This last scenario is a believe what was happening to the students. Here's what they said:

"I was having problems with the Reed Erickson in Boots photo. I went to make some corrections, and I keep getting an error page when I got to save it. Beyond that, when I go to fix it, I have to reselect the Institution and Collection fields, which seems like a bad sign, and again, I'm having trouble saving it. However, the object appears to be showing up just find regardless? I took a screen shot of the error page and saved it on the main desktop just in case."

**Comment by scande3** [comment]
So it happens randomly in the above? Or is there a "Reed Erickson in Boots" record that continually gives the error everytime? (Just easier to debug if I can reproduce it).

**Comment by kjrawson** [comment]
It's happened with two records from the Erickson collection––the boots one and the family one (where he's crouching next to his daughter). I haven't seen it happening elsewhere, but haven't been doing extensive record-level edits.

**Comment by scande3** [comment]
This issue seems to be caused by invalid EDTF dates. Fixing the verification check now but an example is (when logged in):
https://www.digitaltransgenderarchive.net/files/bg257f06r/edit

which has a date issued of:
1974?/200?

(I believe this would be 1974?/200u? , unless I am incorrect). It has also lost its institution / collection information from the attempt to save with a bad EDTF date. So I'll fix the validation and try to generate a list of objects affected... but just wanted you to verify as well and provide an update. Thanks!

**Comment by scande3** [comment]
Code was update to validate on edit. Previously it was only validating EDTF on create and then errors from bad date updates caused a few issues that need to be fixed below.

Needs institution / collection fixed along with edtf (the one mentioned above): https://www.digitaltransgenderarchive.net/files/bg257f06r/edit

EDTF errors for (may or may not have institution / collection missing):
https://www.digitaltransgenderarchive.net/files/qr46r0849/edit
https://www.digitaltransgenderarchive.net/files/t435gd000/edit
https://www.digitaltransgenderarchive.net/files/hh63sv97t/edit
https://www.digitaltransgenderarchive.net/files/t722h8842/edit

Items missing a collection (may duplicate EDTF list):
https://www.digitaltransgenderarchive.net/files/t148fh143/edit
https://www.digitaltransgenderarchive.net/files/t435gd000/edit
https://www.digitaltransgenderarchive.net/files/x346d418q/edit
https://www.digitaltransgenderarchive.net/files/3t945q78b/edit
https://www.digitaltransgenderarchive.net/files/fx719m48m/edit
https://www.digitaltransgenderarchive.net/files/t722h8842/edit
https://www.digitaltransgenderarchive.net/files/fn106x94r/edit

Items missing an institution:
https://www.digitaltransgenderarchive.net/files/x346d418q/edit
https://www.digitaltransgenderarchive.net/files/t722h8842/edit

**Comment by kjrawson** [comment]
Thanks, Steven. I'll pass this along to the students and I'll work on the fixes tomorrow.

**Comment by kjrawson** [comment]
I believe I've fixed all of these errors. So you've added a validation to the edit stage which should prevent these issues? I am going to do another training with the students on EDTF––those errors were pretty bad.

Thanks!

**Comment by kjrawson** [comment]
This seems to be fixed now.
