### ISSUE TITLE
Date display on front end

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#51]
Once we're ready to start polishing the display, one of the first aspects to improve should be the date display. It would be particularly helpful to translate the season codes from EDTF into the words for those seasons (e.g., spring, summer, etc.) and the slashes for the date ranges into dashes so that it is clearer what they indicate. Thanks!

**Comment by kjrawson** [comment]
Make temporal coverage visible when date display is changed

**Comment by scande3** [comment]
The date display was improved to be more human readable. Let me know how that looks or if some of the human readable versions might need to be adjusted.

Temporal coverage should display correctly on those records that have it and use the same human readable format.

Thanks!

**Comment by kjrawson** [comment]
Thanks for your work on this! I am exciting to see these changes. 

For the month display, could you either add a period after abbreviated months or include the full word? I also noticed that the first letters of season codes aren't capitalized. Also, instead of "Date Temporal," could you change the label for temporal coverage to be "Dates Covered"?

Thanks so much!

**Comment by scande3** [comment]
The requested changes should be complete excluding "autumn" that I need to fix. Let me know if it needs further adjustment or if it should be full months rather than abbreviation + period. Thanks!

Commit: 5fc0b451b926debda4fe3011811e34818eca4d80

**Comment by kjrawson** [comment]
The abbreviations look fine. Thanks! I leave this open until Autumn is capitalized, but otherwise it looks good. Thanks!

**Comment by scande3** [comment]
This should now be complete with commit fea6b9103276756ebad9e917e3e7361df7cb7f1b .

**Comment by kjrawson** [comment]
Awesome––thanks!

**Comment by kjrawson** [comment]
I just noticed one minor thing––could you remove the period after "May" since that isn't abbreviated. Thank you!

**Comment by scande3** [comment]
Note: This will be fixed tomorrow around Noon along with making all the human readable date stuff searchable from the text box. Additional question: it is fine for "circa" to remain non-capitalized, correct?

**Comment by kjrawson** [comment]
Yes, it's definitely okay to keep circa lowercase. Thanks!

**Comment by scande3** [comment]
This should now be complete. Commit 9e8f5f44348562ac8bcb3c2149bbf3acb9c4de88

**Comment by kjrawson** [comment]
Looks great. Thanks!
