### ISSUE TITLE
Geoname lookup question

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#52]
From the students:

We wanted to add Long Island (http://www.geonames.org/5125123) to spatial coverage for the Knowledge = Change Pin (https://www.digitaltransgenderarchive.net/files/fb4948489), especially after finding a similar pin by the same creator here http://content.library.ccsu.edu/cdm/singleitem/collection/GLBTQ/id/979/rec/5. But we can't figure out how to add Long Island to our spatial coverage for some reason...

**Comment by scande3** [comment]
It needs to be made better but you should now be able to find "Long Island" under the "Geographic Territory" search section. Added in commit e3cb52220143d190d2dc73a191a6c92c0ae0d1fe.

**Comment by kjrawson** [comment]
Thanks!
