### ISSUE TITLE
Button collection display

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#53]
Hey, Steven.
The students digitized a small collection of pins and buttons that are ready to be made visible but they are displaying a bit strangely. If you are logged in, this link should work:
https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Alison+Laing%27s+Buttons

Any ideas?

**Comment by scande3** [comment]
The command to regenerate thumbnail should now make better thumbnails for these. To do so, you can search for each one from the "View All Files" area and select the option from the drop down next to it. Let me know if this works. Commit: 01faf83a6607782ac277cd8c9173578c01a4a51a . Reference thread on why those commands: http://www.imagemagick.org/discourse-server/viewtopic.php?f=2&t=29517&p=132324

**Comment by kjrawson** [comment]
Looks great! Thank you!!
