### ISSUE TITLE
Unable to change visibility of objects

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#54]
Hey, Steven.
I need to hide a handful of items, but any record edits give me an error and don't change the visibility. Any ideas? Thanks!
<img width="1006" alt="screen shot 2016-03-26 at 6 13 45 pm" src="https://cloud.githubusercontent.com/assets/15388345/14062685/b2ac2950-f37e-11e5-9103-08278e050ff0.png">

**Comment by kjrawson** [comment]
When I pull it up in the file listing and use the drop down to "swap visibility," that seems to work, FYI.

**Comment by kjrawson** [comment]
Emailed about this, too: invisible objects are still searchable through Google. We have a handful of objects that need to be hidden completely, but I don't want to delete them from our system.

**Comment by scande3** [comment]
This has been fixed and a new visibility option added to restrict to only logged in users. This is commit e031c2aa965d6ce46339b1c831981d6229be52a0

**Comment by kjrawson** [comment]
This works perfectly. Thanks so much for attending to it so quickly! The label in the file listing says "Institution Name," FYI.
