### ISSUE TITLE
Solving a minor mystery

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#55]
I have been wringing my hands over a minor but annoying discrepancy––the public-facing collection is showing 698 items if you do a blank search. The problem is that my inventory is at 697. When I've manually added up the items in the collections listing for the public-facing site, that also comes to 697. Is there a way for you to see whether there is one item that is public but isn't in a collection? I am worried that it's related to the items I just made invisible, but those all seem fine. Thanks!

**Comment by scande3** [comment]
This item is the following that is missing a collection: https://www.digitaltransgenderarchive.net/files/s7526c41m

(Likely can add a way to detect this in the future).

**Comment by kjrawson** [comment]
Thank you! That item had been correctly processed before. I have tried to edit it twice now (it belongs in "Alison Laing's Photographs"), but the changes aren't sticking. Can you tell why that might be?

**Comment by scande3** [comment]
Fixed. (In theory, the fix pushed should fix the form). Do see that an update submission is slow... will need to debug that yet.

**Comment by kjrawson** [comment]
Thanks!
