### ISSUE TITLE
News page not displaying image

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#56]
Very minor issue, but I just posted a news story today and the image thumbnail isn't displaying on the news page for some reason.

**Comment by scande3** [comment]
Fixed with commit 92379cdc2bda996b27c674a2acd168604e3ef2ec . (Regular expression for the image detection missed allowing for parenthesis in alt tags).

**Comment by kjrawson** [comment]
Thanks!
