### ISSUE TITLE
IA Harvest Sorting––One File Still Needs to be Ingested 

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#57]
I've now moved all of the materials out of the IA Harvest Collection and I am trying to sort out what we have and what's missing. One challenge has been that when you view the "Transgender Oral History Project" institution, there are supposedly 384 objects in it. But, when you add up the objects in those collections from the collections facet, there are only 354 total. This is similar to our problem with a few issues of LesGirls, a few from TransSisters, and one from Drag that I told you about. 4 other collections appear to be incomplete, based on the 354 breakdowns. Am I missing some somewhere?

**Comment by scande3** [comment]
I'll look into why the counts are off.

As an aside, I added a way to sort the files by Collection Name. This is useful as you can sort it by that either ascending or descending and then go to the last page of the list to see any items missing a collection. (There appears to be two in this state).

**Comment by kjrawson** [comment]
Very helpful! I've fixed both of those files. Down the road, it may also be helpful to sort by visibility so we can see what's been restricted at a glance. No rush on that though. Thanks!

**Comment by scande3** [comment]
I took a look at this and couldn't duplicate it at the moment. Can you give better steps to reproduce this issue? If it isn't an issue currently, can you let me know if it occurs again? Thanks!

**Comment by kjrawson** [comment]
The numbers are aligned now...must have been a processing lag. That means that overall, we're missing 6 items from IA. I sent you the links for 5 of them already, but here they all are:

- https://archive.org/details/lesgirlsboyswill00unse
- https://archive.org/details/lesgirlsboyswill00unse_0
- https://archive.org/details/transsistersjour00unse_0
- https://archive.org/details/transsistersjour00unse
- https://archive.org/details/drag00leeg
- https://archive.org/details/enfemmemagazine00unse_0   [this is the only one I hadn't sent before]

Thanks!

**Comment by kjrawson** [comment]
Got the last one. Thanks!
