### ISSUE TITLE
Explicit content in collection thumbnail [Need ability to set collection thumbnail]

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#58]
Hey, Steven.
The thumbnail that was grabbed for "Lee G. Brewster's Mardi Gras Ball" collection is explicit: https://www.digitaltransgenderarchive.net/col/cf95jb495. It would be helpful to be able to use the other thumbnail instead.

**Comment by scande3** [comment]
While a way to specify the thumbnail needs to be added, the collections will no longer use thumbnails from items that are "Explicit content in thumbnail". 

This is part of commits 92379cdc2bda996b27c674a2acd168604e3ef2ec , 07786fdee7b0caefb887f2956b361dd5d5f5858f , and da30b6fc20cc500104d15efa418f6e36eebab266

**Comment by kjrawson** [comment]
Thanks!

**Comment by kjrawson** [comment]
Works great!
