### ISSUE TITLE
Thumbnails not generating

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#60]
Hey, Steven.
The students were having trouble with thumbnails today––many didn't generate. They scheduled them to regenerate, but that didn't have any immediate impact. Thanks!

**Comment by scande3** [comment]
This items were uploaded without an image. (Items hosted elsewhere do not require an image... should this change to where it is required so they cannot ever submit without one?).

The edit functionality to add an image after an item was created has not been implemented yet. I'll add functionality for this tonight along with the flagged thumbnail. 

So... in short... they will need to add an actual image to those items tomorrow.

**Comment by kjrawson** [comment]
Ah, that makes sense. Sorry for the errors on our end! It will be helpful to be able to add images after an item is created––that should be enough to meet our needs without requiring an image.

**Comment by scande3** [comment]
You should now be able to upload a file for those items that will generate a thumbnail. It is recommended to test with one first to ensure that it is working as anticipated. Let me know if you notice a problem.

This is part of commits 92379cdc2bda996b27c674a2acd168604e3ef2ec , 07786fdee7b0caefb887f2956b361dd5d5f5858f , and da30b6fc20cc500104d15efa418f6e36eebab266

**Comment by kjrawson** [comment]
Works great––thanks!
