### ISSUE TITLE
Hyperlink format in collection abstract

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#61]
Hi, Steven!
The students would like to include a link in this collection abstract: https://www.digitaltransgenderarchive.net/col/cc08hf66m. Is it possible to accommodate that? Thanks!

**Comment by scande3** [comment]
I added html code to make that a link: https://www.digitaltransgenderarchive.net/col/cc08hf66m . Does more need to be done?

**Comment by kjrawson** [comment]
That works great, thanks! Will it now be possible to include links in any abstract or should we do it on a case-by-case basis? If it's the latter: we haven't needed it often, so it's probably not worth spending much of your time coding to fix something that has only come up once.

**Comment by scande3** [comment]
HTML shouldn't be used in the description of an actual object. For collections, it should be fine to add HTML links for now as I did. Can revisit it should a better approach be thought of in the future?

**Comment by kjrawson** [comment]
Sounds good. Thanks!
