### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#62]
From a student (and I replicated it):
Error Message:
https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Transgender+Tapestry&page=4&sort=title_primary_ssort+asc%2C+dta_sortable_date_dtsi+asc 
So I was on this^ page looking through the Transgender Tapestry and when I hit next the error message popped up. I also tried switching the display pages to "Show 50" and tried to go to the next page and again an error popped up.

**Comment by scande3** [comment]
Sorry about that. Fixed in commit adf770bb6e1306b40195a291831a3f73ca666106

**Comment by kjrawson** [comment]
Thanks!
