### ISSUE TITLE
Metadata periodically lost for already processed materials {On hold until it recurs}

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#63]
Hi, Steven. 
This is probably going to be a tough one. When I initially moved the Transgender Tapestry collection out of the IA collection, there were 106 items in that collection. As the students have been processing it over the past few weeks, somewhere along the line a handful of items have lost their collection metadata (and for some, their institution). I've found and restored about 5 of them so far. But here's an example that I haven't fixed: https://www.digitaltransgenderarchive.net/files/dv13zt26k. 

Even more concerning is another example I found from a collection that was fully processed and posted online correctly, TransSisters. Somehow, this item lost its collection metadata even though it hasn't been edited since we made it public: https://www.digitaltransgenderarchive.net/files/bg257f11m. 

I am guessing that I am missing others. You may be able to do a search for missing collections, as you've done in the past, but it seems like something more systematic is happening, some sort of glitch.

Hopefully this is enough info to go on!

**Comment by scande3** [comment]
I'll do a search later. Please provide other information as you notice it. (For example, while your last example had never been edited, had that collection ever had its information changed? Or did you ever try to swap its visibility or thumbnail prior to it losing that link?).

Thanks!

**Comment by kjrawson** [comment]
Will do!

**Comment by kjrawson** [comment]
Here are some additional ones the students were having trouble with:

- Transgender Tapestry Pen Pals: https://www.digitaltransgenderarchive.net/files/mk61rh01q
- The TV-TS Tapestry Issue 57 (1991): https://www.digitaltransgenderarchive.net/files/kd17cs934
- The TV-TS Tapestry Issue 66 (Winter, 1993-1994): https://www.digitaltransgenderarchive.net/files/dv13zt26k

Some of these (the last two, I believe) were edited by the students and the error appears to have occurred after re-saving it.

**Comment by kjrawson** [comment]
Here are some ones that I just changed tonight because we made that collection visible:

- https://www.digitaltransgenderarchive.net/files/ws859f76k/edit
- https://www.digitaltransgenderarchive.net/files/fj2362157/edit
- https://www.digitaltransgenderarchive.net/files/mk61rh01q/edit
- https://www.digitaltransgenderarchive.net/files/vh53wv82z/edit
- https://www.digitaltransgenderarchive.net/files/cf95jb48w/edit
- https://www.digitaltransgenderarchive.net/files/br86b364d/edit
- https://www.digitaltransgenderarchive.net/files/dv13zt26k/edit
- https://www.digitaltransgenderarchive.net/files/w0892b00c/edit

**Comment by kjrawson** [comment]
This happened again this morning. I was viewing a just-processed collection from the back end and I clicked "Make All Visible." During that process, about 6 items lost their collection metadata...at least it doesn't display in the files listing and those objects that didn't have it were not made visible. Here's one example: https://www.digitaltransgenderarchive.net/files/qz20ss54w. Though it shows the correct collection in that record, if you click "edit," you'll see that nothing is selected in the dropdown. I've edited the others because I wanted to post the collection.

**Comment by scande3** [comment]
So potentially a flaw in the make all visible command? Will take a look at that then. Thanks!

**Comment by kjrawson** [comment]
That would be my guess. And I am thinking that's when it happened the last times as well. Thanks!

**Comment by kjrawson** [comment]
We have two files that are ready to post, but they keep losing their collection and institution metadata when you look at the record: 

https://www.digitaltransgenderarchive.net/files/6395w7174/edit?tab=descriptions
https://www.digitaltransgenderarchive.net/files/qr46r090f/edit?tab=descriptions

**Comment by scande3** [comment]
What collection / institution are they supposed to belong to?

**Comment by kjrawson** [comment]
DTA/Die Transvestiten

**Comment by scande3** [comment]
This should now be fixed with commits 80f4b3aeeb7666a88449d226ea6eb93a712e7af2 and 2e62a7393df76dbb63c9d911b5be48cf912e8ab9

There will be one more commit to clean up the solution a bit. Hopefully this then fixes what was this recurring issue.

**Comment by scande3** [comment]
In addition, it seems this bug hit one other item of: https://www.digitaltransgenderarchive.net/files/qz20ss54w/edit (if you want to add its collection / institution information).

**Comment by kjrawson** [comment]
Great, thanks! I've made the Hirschfeld collection public and fixed the other record (I was keeping it incorrect so you had an example to work with). I'll keep this ticket open until you add another commit. Thanks for your work today!

**Comment by kjrawson** [comment]
We'll close this, because I believe it was fixed with the other ticket you just completed.
