### ISSUE TITLE
Display order within large collections

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#64]
Hey, Steven.
Here's a comment from the students about displaying the Tapestry collection (which isn't public yet):
- The display order is a little wonky. I know the changing titles affect it some, but there's also instances like the 5 newsletters with the same title that appear in order of 11, 10, 7, 8, 9 and I tried removing the "#" to see if that would change it, but alas, it did not. Something similar happens once you hit the 100s as well.

I am thinking this is actually about the numbers in the title (and this collection is a bad example because the title changes a few times), but I am not sure if it's possible to code it so that the titles would display in order of the issue.

**Comment by kjrawson** [comment]
--Fix date sort to include month and day
--change sort order to oldest to newest for collections views

**Comment by kjrawson** [comment]
Hey, Steven!
When I sort a collection by date, the display seems to be picking up the numbers of the months and sorting it by that, rather than the correct order of months. Could you take a look at this when you get a chance. Thanks!

**Comment by scande3** [comment]
Some work has progressed on this issue. Notably that the sorting of dates does take month into account when sorting by date in one's results. Additionally, clicking the "View All Items" link on a collection page now sorts by date: https://www.digitaltransgenderarchive.net/col/7w62f824d

There are a few remaining issues:

1. Where else should it prioritize "date" beyond the "View All Items" link there? Furthermore, should the default result order elsewhere in the site be: relevance than date then title? Currently the default is to sort on relevance first, then by title which is how it is usually done.

2. Can you clarify the January 5th comment? If I sort by date created, the collections seem to work. Sorting by date within the admin collection view doesn't work as we don't store date information on the collection. Unless the date range a collection covers should come from the items within it?

Thanks!

**Comment by kjrawson** [comment]
This is great, Steven. Thank you! In terms of the second issue, you actually fixed exactly what I was talking about, so that's all set. 

In terms of your first question, I can't immediately think of other places where you need to change the sort order. I'll close the ticket for now, but if I notice others, I'll reopen it.

Thank you!
