### ISSUE TITLE
Alphabetizing error in "Topic" (Very minor)

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#65]
Hey, Steven.
I almost didn't mention this because it's so trivial, but when you sort Topic alphabetically within the Outreach Newsletter collection, "Police Brutality" comes first. Maybe there's a space before it? It goes without saying, but no rush on this one.

![policebrutality](https://cloud.githubusercontent.com/assets/15388345/14904881/d450ce48-0d79-11e6-904a-8fecfd3ee80f.jpg)

**Comment by scande3** [comment]
All facets are now case-insensitive. This includes cases when viewing two terms that had the same hit count (ie. it will display them in case-insensitive order for those items with the same number of facet hits). Fixed in commit 39436e64c2d4dfdd998ae7f9bec0e0b4824851f0

**Comment by kjrawson** [comment]
Thank you!
