### ISSUE TITLE
News thumbnail not generating

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#66]
Hi, Steven!
We had this issue once before: we have one news story that includes an image that doesn't seem to be generating a thumbnail. Nothing major, but just wanted to let you know about it. Thanks!

**Comment by scande3** [comment]
Fixed in commit 8b2d0626728366a33c031d24e5c938df32498ed0

**Comment by kjrawson** [comment]
Thanks!
