### ISSUE TITLE
Homosaurus links not working

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#67]
Hey, Steven!
I am working with the author of the Homosaurus on the presentation that he's giving in June. He noticed that the "hierarchy" links on each term's page on the site aren't working. Do you know if/when those might be workable? 
Thanks!
K.J.

**Comment by scande3** [comment]
If there is interest in promoting the site, then can fix that and update other aspects of it this weekend.

There is the SPARQL endpoint and different formats beyond html (like ttl and jsonld) to add. Did you both ever add any links to LCSH in the vocabulary? Anything else that might be needed?

**Comment by kjrawson** [comment]
That would be great! We didn't add LCSH links––we wanted to revise the vocabulary first and then do the work of connecting the terms as part of that effort. I can't think of anything else, but thanks!

**Comment by scande3** [comment]
Fixed this - though I'll likely still update the display of the information at some point. In addition, the "other formats" links now work and you can get a response for the entire vocabulary in various formats at the bottom of: http://homosaurus.org/terms

Beyond style fixes, a SPARQL endpoint still needs to be added to the site.

This was the following commit: https://github.com/CollegeOfTheHolyCross/homosaurus_site/commit/2fb3db6b28f0f0283f922f23603ea5ad46bce7c0

**Comment by kjrawson** [comment]
Great––thanks!
