### ISSUE TITLE
Related Terms in Homosaurus

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#68]
Hi, Steven!
I just realized that Related Terms aren't showing up on homosaurus.org, though are inputted. Is that difficult to do? It would be great if we can get that up and running before the last week of June when Jack is giving a talk on the Homosaurus. Thank you!

**Comment by kjrawson** [comment]
I just found out that IHLIA (the archives in Amsterdam that created the homosaurus) uses it in a pretty interesting way on their website. If you go to http://www.ihlia.nl/collection/collection-of-ihlia/?lang=en and do a search for hiv/aids, you'll see how they represent it in graphic form. It seems a bit clunky, but thought you might want to check it out.

**Comment by scande3** [comment]
Related Terms were added to the HTML display. Also made some improvement to the site to hopefully improve the UI and added a search interface. Can likely still be better eventually but let me know how this looks and works. This is commit 39436e64c2d4dfdd998ae7f9bec0e0b4824851f0

**Comment by kjrawson** [comment]
Looks and works great. Fantastic!
