### ISSUE TITLE
Header display in Safari

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#69]
Hi, Steven. There appears to be a problem with formatting the header in Safari. I've attached a few screenshots for you to see. Thanks!

![banner](https://cloud.githubusercontent.com/assets/15388345/15517567/719e073c-21c6-11e6-94d4-74d2c9e1dced.jpg)
![banner2](https://cloud.githubusercontent.com/assets/15388345/15517569/735f4d10-21c6-11e6-8010-02d682460246.jpg)

**Comment by scande3** [comment]
Should be fixed in commits a489f1befd3eff3e0b6f9a6e3a73803877884abd and 2ed5d3e532c03aae8fc4bf9b1bdbf37477a36678

Let me know if you notice anything else odd and hopefully didn't affect any other browsers with this fix. Thanks!

**Comment by kjrawson** [comment]
Perfect––thanks!
