### ISSUE TITLE
Front end display preference: indicate current page with underline?

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#71]
Hi, Steven!
There's no rush on this, but it would be helpful to indicate which page a visitor is on when navigating within search results. Maybe just an underline below the current page number?
Thank you!

**Comment by scande3** [comment]
An indication to for the current page was fixed in commit 3c71454265eb13806e700061928bf45376589b35 . Let me know if that works.

**Comment by kjrawson** [comment]
Wonderful––thank you!
