### ISSUE TITLE
Auto add cursor to lookup fields

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#73]
When opening a lookup session in the Homosaurus, LCSH, Geonames, etc., it would speed up workflow to have the cursor automatically be in the search field.
Thanks!

**Comment by scande3** [comment]
Should be completed as of commit 253d46fc4e5bd339df2227c53826fec3bfc73dc7

**Comment by kjrawson** [comment]
There will be a celebration in the lab over this one :) Thank you!
