### ISSUE TITLE
Build a harvestable endpoint [Any timeline on harvesting?]

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#76]
Aiming to have it harvested into DC by end of 2016

**Comment by scande3** [comment]
DPLA plans to use a method known as ResourceSync in the future for harvesting (and which Digital Commonwealth would also support). Sadly, they don't plan to do work on that until the end of this year and Digital Commonwealth doesn't have time to code that specification in Hydra.

So, for now, a OAI-PMH endpoint has been created. You can view sets at: https://www.digitaltransgenderarchive.net/oai.xml/?verb=ListSets

Once can view records at (may take a few minutes to load as not optimized):
https://www.digitaltransgenderarchive.net/oai.xml/?verb=ListRecords

You can resume the list using a resumption token like:
https://www.digitaltransgenderarchive.net/oai.xml/?verb=ListRecords&resumptionToken=100

This weekend will add in the ability to look up a single record based on the identifier and clean up some of the code itself for this to be usable for harvest. Please let me know if you do notice any errors in the meantime.

Thanks!

**Comment by kjrawson** [comment]
Awesome! Thanks, Steven! I will be out of town from Mon–Thurs of next week (8/8–8/11), FYI. But, I am looking forward to digging into this more when I get back to DTA stuff on Friday. Thank you!!

**Comment by scande3** [comment]
Ability to look up a single record (OAI's GetRecord) added in commit: 253d46fc4e5bd339df2227c53826fec3bfc73dc7

Sample: https://www.digitaltransgenderarchive.net/oai.xml/?verb=GetRecord&identifier=5138jd84x

**Comment by kjrawson** [comment]
I believe this is all set now!
