### ISSUE TITLE
Language field not working

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#78]
Hi, Steven.
The language field in the intake form doesn't appear to be working. When you hit the plus sign and try to add a new language (I was trying to add "German"), there seems to be a very short list that pops up, regardless of what letters are entered. 
Thanks!

**Comment by scande3** [comment]
I think I know what this issue is. Pushed up a fix but didn't test it yet if you can let me know if it is fixed? Thanks.

**Comment by kjrawson** [comment]
It's a bit inconsistent. It doesn't fill in the type-ahead, but seems to populate when you hit the backspace key. Thanks for working on this so quickly!

**Comment by scande3** [comment]
Try it once more. Forgot one step. If there is still an issue, will look at it tonight.

**Comment by kjrawson** [comment]
It's perfect. Thank you!!
