### ISSUE TITLE
Searching full text OCR

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#79]
Hi, Steven.
Following what we do with the materials hosted on IA, could we make the items we host full-text searchable? Thanks!
K.J.

**Comment by scande3** [comment]
Full text of almost all PDFs should now be searchable. However, the OCR on many of the PDFs is far from perfect. Plus there are a few that were created improperly that won't have OCR text as the library being used to parse it isn't as fault tolerant as Adobe PDF reader. Those that are incorrect will be added as a comment to this ticket later today.

In addition, I've adjusted the default search weight of many different fields. Please feel free to do a bunch of free text searches and let me know if the relevancy seems strange in some cases.

Commits:
27ad11f494893ab89765a31cd6f1bf22ff2dad83
1c18090e05a84e34560a95ae46c012be6f40f7ba
21b1cc677a852374ff7cb43ec611806aa8d39978
d8ef78b93a3e3a366b114863ac8173620d63edb6
01b9780e79f51732ab6c58bd7045edd8ef40704e
91303e58c76bf7565492e6d486360cf9227ed1b3
05f39157cffb0bcebc6ab5916aa1ae26b07866d1
e98ccfaea6edf1f843f19b3366b9f2c0da5f63a0

**Comment by kjrawson** [comment]
Thanks for this update, Steven! I'll work on doing some searches later today and I'll send you some feedback if anything seems strange. I'll also be happy to try to redo the OCR on the ones that are faulty.

**Comment by scande3** [comment]
List of PDF objects that failed to generate OCR: 

"7m01bk68h", "sx61dm28w", "0p0966899", "qb98mf45k", "b8515n370", "st74cq46k", "dz010q056", "ff3655282", "br86b3588", "79407x177", "sj139194f", "js956f82z", "st74cq484", "pn89d657h", "fb494842n", "1z40ks82j", "xp68kg235", "q237hr94j", "bc386j25q", "4m90dv529", "h128nd70b", "2z10wq25s", "bk1289909", "8s45q882q", "tt44pm87g", "rf55z7713", "qj72p716m", "p8418n27h", "sj1391978", "kh04dp73w", "j67313792", "12579s27c", "gm80hv387", "dz010q06g", "nz805z73k", "vx021f09b", "gb19f5810", "8623hx78c", "vt150j271", "m326m174z", "qz20ss512", "rj430458x", "g445cd17d", "4q77fr398", "w08929960", "pz50gw11f", "9019s246n", "xw42n796z", "v118rd525", "wh246s153", "mp48sc79x", "3n203z148", "1544bp10f", "cr56n104t", "sq87bt61f", "9k41zd51t", "vt150j29k", "9k41zd523", "2801pg33n", "fb4948489", "0z708w436", "rv042t11v", "0p096691b", "ns064605c", "1831cj94h", "44558d32r", "cc08hf685", "vd66vz95s", "fj236217s", "2227mp72v", "4f16c291q", "8623hx80d", "db78tc124", "zc77sq15b", "1n79h4363", "vt150j34f", "ng451h55k", "1z40ks907", "2801pg37r", "x346d424v", "4f16c2920", "9019s2532", "zc77sq16m", "j098zb17n", "0k225b092", "t722h889f", "0v838060s", "qb98mf60p", "m613mx61z", "1n79h437c", "12579s30p", "76537143s", "4f16c2938", "1r66j1174", "9c67wm898", "xk81jk45p", "qf85nb36v", "pc289j13p", "rf55z776g", "sq87bt68c", "xd07gs82c", "xp68kg260", "vh53wv85s", "cc08hf69f", "7s75dc423", "765371442", "xw42n799s", "0c483j43w", "wh246s22h", "vx021f19k", "f7623c688", "3r074v00f", "1j92g7537", "vt150j35q", "pr76f350t", "pk02c984x", "3r074v01q", "tq57nr05z", "gt54kn11k", "s7526c460", "4j03cz73v", "sf2685161", "8g84mm373", "jq085j99x", "k0698760q", "7w62f826z", "7s75dc44n", "g732d900g", "gt54kn12v", "cr56n110z", "tt44pm955", "bk128998h", "wm117p04t", "gm80hv433", "gx41mh91j", "mw22v551q", "736664606", "rx913p990", "xw42n7888", "2b88qc16g", "r494vk17h", "zp38wc617", "ws859f64s", "1r66j116v", "0p096692m", "bz60cw251", "xk81jk42v", "wm117p00q", "qj72p712h", "vq27zn431", "vh53wv730", "fx719m462", "rb68xb899", "2514nk502", "2b88qc181", "t148fh19g", "rb68xb902", "hd76s006h", "xg94hp60j", "rb68xb91b", "2514nk53w", "8336h195z", "9w032304k", "cv43nw87f", "6h440s51f", "5712m658s", "4j03cz719", "5712m6592", "8c97kq48c", "g732d901r", "3b5918592", "37720c78r", "c247ds117", "zc77sq17w", "zc77sq185", "8p58pd01g", "8p58pd02r", "bn999678h", "0r9673801", "w9505052n", "k930bx056", "12579s31z", "sj139199t", "8336h197h", "zc77sq21g", "0k225b10t", "hm50tr794", "1v53jx02k", "sq87bt673", "2z10wq28m", "4b29b601h", "h415p9589", "8c97kq50d", "3r074v020", "9593tv18r", "m613mx63h", "sb397828k", "12579s33h", "rb68xb95f", "xg94hp623", "cf95jb541", "s4655g63d", "t148fh22s", "2r36tx615", "wd375w32h", "d791sg22v", "mp48sc83h", "gt54kn06q", "n009w234m", "b2773v766", "41687h50f", "tq57nr067", "6h440s52q", "2v23vt41x", "2v23vt426", "b2773v77g", "sb397830m", "b2773v78r", "jm214p16v", "k930bx06g", "2n49t1788", "5t34sj62z", "41687h51q", "5x21tf45j", "n009w237f", "n009w238q", "k930bx07r", "bc386j278", "mp48sc84s", "v979v313f", "sn009x848", "0z708w461", "6t053g07w", "sn009x85j", "3197xm11z", "x059c738z", "td96k256m", "02870v887", "1g05fb64j", "sb397831w", "xk81jk434", "rr171x28s", "rr171x292", "p8418n292", "1j92g755s", "p8418n30t", "qz20ss54w", "pz50gw15j", "0g354f299", "5d86p030t", "rr171x30t", "2801pg381", "9306sz356", "0g354f302", "gq67jr234", "fn106z01z", "nc580m720", "gf06g270q", "t435gd03t", "5d86p0313", "jw827b737", "5d86p032c", "kw52j808s", "0z708w48k", "0g354f31b", "jh343s363", "vt150j360", "2j62s4901", "wm117p03j", "nv935289d", "kw52j810t", "st74cq530", "t435gd043", "pz50gw16t", "sx61dm36k", "0g354f32m", "m039k4971", "3b5918656", "3b591866g", "jw827b75s", "qr46r089p", "6395w715k", "bn999679s", "hm50tr80w", "44558d36v", "4x51hj08r", "hm50tr815", "02870v908", "kw52j813n", "fn106z04s", "rj4304642", "wh246s23s", "0z708w51w", "x346d423k", "wp988j948", "pz50gw173", "w37636860", "pn89d666g", "gb19f587n", "cn69m420z", "2j62s492k", "ww72bb58w", "st74cq55j", "gh93gz56x", "44558d374", "0g354f33w", "9593tv24w", "3197xm127", "sj139200c", "ng451h56v", "9306sz381", "6m311p359", "h702q650b", "m039k499k", "5d86p034x", "44558d38d", "fn106z052", "dr26xx42q", "8k71nh16k", "jh343s37c", "t435gd06n", "3j333233d", "4j03cz744", "2v23vt44r", "b5644r59s"

**Comment by kjrawson** [comment]
That's quite a list! I think I'll add it to the work for the lab in the fall––it would take me too long to fix and re-upload all of these. Thanks for sending them!

**Comment by kjrawson** [comment]
A few of these do seem text-readable. See https://www.digitaltransgenderarchive.net/downloads/rb68xb95f and https://www.digitaltransgenderarchive.net/downloads/2b88qc181

Any idea why those would raise flags?

**Comment by scande3** [comment]
The first is due to that being a .docx document rather than a PDF. I had assumed the documents being uploaded were PDFs... so may have to adjust for that since I didn't know that content type was being used in the system?

I think I see the issue with the 2nd object. So the list may shrink when I rerun the script later tonight with that fix.

Thanks!

**Comment by kjrawson** [comment]
I didn't realize we were posting word docs either (though I was the one that did that!). Do you have any thoughts on whether we should avoid docs? It displays and downloads like a PDF for viewers,I noticed.

**Comment by scande3** [comment]
It appears the file is a PDF. I'm unsure why the title is what it is when it is opened which had originally confused me. As it isn't from the application, I'll need to explore the file's metadata more to see where that might have been set?

I re-ran some fixes to the process and edited the list of documents that were problematic. Are there more from that list that should have processed?

Have you run any search experiments yet btw?

Thanks!

**Comment by kjrawson** [comment]
Thanks, Steven! So is the list in the comment above the most current list of the problematic files? I'll have the students fix those when the lab resumes in the fall. And I have done some search tests and haven't seen anything strange yet. All has worked well so far!

**Comment by kjrawson** [comment]
I just wanted to double-check: is the list above the most current one for files that do not have proper OCR?

**Comment by scande3** [comment]
It is. I can run a script again to verify if needed?

**Comment by kjrawson** [comment]
No problem. I'll let you know when the students are done with it, then perhaps you can run the script again to make sure they got them all. Thanks!

**Comment by kjrawson** [comment]
I wanted to let you know that the students have completed this project. There were a handful that didn't need OCR because they were images, and a few others that failed to generate OCR. But I were able to fix the vast majority. Thanks!
