### ISSUE TITLE
Strange issue with Duke University finding aids

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#80]
Hey, Steven!
We have three finding aids from Duke, which you can find from a [collections search](https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=Duke+University+Finding+Aids). However, when you browse by institution, Duke, there are no results: https://www.digitaltransgenderarchive.net/catalog?f%5Binstitution_name_ssim%5D%5B%5D=Duke+University+Libraries. Any ideas? Thanks!

**Comment by scande3** [comment]
Fixed for this case. Should have a fix tomorrow for it in a more broad sense.

Am I right in assuming you had changed the Institution name prior to this occurring? Thanks!

**Comment by kjrawson** [comment]
I am not sure. If so, it would have been a while ago. Thanks!

**Comment by scande3** [comment]
This should be able to be closed as a generic fix was pushed up as part of commit: 27ad11f494893ab89765a31cd6f1bf22ff2dad83

Feel free to reopen if this occurs again. Thanks!

**Comment by kjrawson** [comment]
Great, thanks!
