### ISSUE TITLE
Two books––large files take a long time to open

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#82]
Hey, Steven!
There are two new records & objects that we are almost ready to upload (after the metadata issues are resolved), but I wanted to check in with you about the size of the files. They are high quality PDFs and take a very long time to open (since they are so long, too). Do you think that's okay?

**Comment by scande3** [comment]
Up to you on that and how it works for the user experience, I believe. The only real solution is to support having each image be its own file rather than the current setup of only a single PDF that contains all the images.

**Comment by kjrawson** [comment]
Okay, just wanted to check in with you. Perhaps we'll add something to the description that indicates that it could take a while to download. Thanks!
