### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#84]
Hi, Steven!
Now that we have some materials in another language, I wonder if it's time to display language in the metadata and possibly as a (collapsed) facet? We'll be getting some additional things in other languages in the coming weeks. Thanks!

**Comment by kjrawson** [comment]
Strange...I am seeing the language display in most records, but not here: https://www.digitaltransgenderarchive.net/files/qr46r090f

**Comment by scande3** [comment]
Fixed the language display in commit b4e3ecfed8347f7c16171983b234d41197c89c46 . Do you want the language facet as you have it as a question above? I don't think many people generally wish to facet on that type of data but I could be wrong?

**Comment by kjrawson** [comment]
Thanks, Steven! Let's just leave it as a display in an item's record for now. I might revisit this once we have a lot more materials in other languages. It's a pretty popular search feature in larger databases, but we're probably not there yet.
