### ISSUE TITLE
Thumbnail display in search results

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#86]
I've noticed that it's fairly common for thumbnails to appear broken in search results. See if this shows any broken thumbnails for you: https://www.digitaltransgenderarchive.net/catalog?f%5Bcollection_name_ssim%5D%5B%5D=International+TranScript+. When you click on the object, it's there and the thumbnail is fine. Then, if you back out, you'll then see the thumbnail in the search results without a problem. Perhaps it's a browser issue?

**Comment by scande3** [comment]
What browser are you using? Chrome, Firefox, Safari, or a mixture that shows this behavior?

**Comment by kjrawson** [comment]
Appears to be in Chrome only

**Comment by kjrawson** [comment]
This happened in a new case today––I added University of Wisconsin as a new institution and their logo is showing up fine everywhere but in my Chrome browser. I tried uploading both a tif and jpeg, but there was no difference. Maybe this is just my browser issue?

**Comment by kjrawson** [comment]
Appears to be resolved––must have been an out-of-date browser issue.
