### ISSUE TITLE
No way to delete Institution

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#87]
Hi, Steven!
I am trying to delete this Institution: https://www.digitaltransgenderarchive.net/institutions/6h440s484, but there doesn't seem to be a way to do it. Thank you!

**Comment by scande3** [comment]
Functionality added in commit 06f1045df828db9cd681ccd94d6ee157c2625d70 . Let me know if you notice any issues with it whenever you do use it. Note that any delete is permanent and will remove that institution information from any collection or object that was related to that institution (but won't delete those collections / objects). Thanks!

**Comment by kjrawson** [comment]
Thanks for setting it up this way! I just deleted the one I had needed to get rid of––worked perfectly!
