### ISSUE TITLE
Editing files issues

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#88]
Hi, Steven.
When we go into a file to edit, it appears to strip off the collection and institution metadata and we need to re-enter it before saving. Any idea why that might be happening?
Thanks!

**Comment by scande3** [comment]
This should be fixed now in commit 06f1045df828db9cd681ccd94d6ee157c2625d70 . Let me know if you see any additional issues. Thanks!

**Comment by kjrawson** [comment]
Great. Thank you!

**Comment by kjrawson** [comment]
The students from today reported that they continued to have issues with this. They were working on the Erickson Educational Foundation Newsletters, FYI. Thanks!

**Comment by kjrawson** [comment]
I believe this should be all set from your latest commit. I'll close it for now. Thanks!
