### ISSUE TITLE
Spatial Coverage Lookup Not Working

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#89]
Hi, Steven.
The students are trying to add new records and they haven't been able to get the Spatial Coverage lookup working. Thanks!

**Comment by scande3** [comment]
Fixed in commit 06f1045df828db9cd681ccd94d6ee157c2625d70 . Issue was when I ran the dependency update in the News Tags commit. (Their release was broke the functionality from another code dependency, issue: https://github.com/crohr/rest-client-components/issues/13 ).

**Comment by kjrawson** [comment]
Perfect. Thanks!
