### ISSUE TITLE
Losing metadata again when editing records

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#91]
Hi, Steven.
I was just trying to edit metadata for a few records within the Metamorphosis collection. Before I started editing records, the collection had 26 items. It now has 23 and I can't seem to find the 3 that are missing! I am guessing the metadata wasn't properly saved again when I made the edits? I appreciate your help in figuring this out!
K.J.

**Comment by scande3** [comment]
K.J.,

No items are showing a loss of collection information. It may be the collection object having an issue. Which collection where you editing items from?

Thanks!

**Comment by kjrawson** [comment]
It was the Metamorphosis collection that I was struggling with. All 26 seem to be showing up now. I wonder if there is a lag somehow? One of my students, Michael, said he had some trouble with the Erickson Foundation Newsletters, too. Thanks for looking into it!

**Comment by kjrawson** [comment]
The Metamorphosis collection is giving us more trouble today. The students were editing records and it kept taking the edited records out of the collection. I ended up taking them all out, but now it's not letting me batch add them back to Metamorphosis. There should be 26 items in there.

**Comment by scande3** [comment]
You took them all out and then tried to put them back in via batch?

Will try to look at the batch move tonight. Can you tell me some of the items that should be in there since they were dis-associated?

**Comment by kjrawson** [comment]
Yes, we tried to do a batch add after we had lost about 9 of them from the collection when students had gone in to edit the records. I just checked it and it appears that all of the Metamorphosis issues are now in the right collection––so the batch add took several hours to process and it completed it in the background (I waited about 15 minutes with it still loading in the pop-up window and I ended up closing it when there was no response). So unfortunately, I don't have any records with outstanding errors to send you to.

**Comment by kjrawson** [comment]
Okay, I just edited a record and it lost the collection info. The only thing I edited was the title. Here's a search where you can see it (when logged in):
https://www.digitaltransgenderarchive.net/catalog?utf8=%E2%9C%93&tab=descriptions&search_field=all_fields&search_field=all_fields&q=metamorphosis+vol.+1

It's Metamorphosis Vol. 1 No. 3. Here's the record: https://www.digitaltransgenderarchive.net/files/5x21tf49n. 

I won't fix it until you get a chance to look at it. Thanks!

**Comment by scande3** [comment]
This record has the correct Collection attached to it again. I've made a code update that might resolve this issue. Let me know if it seems to have done so or if you notice it occurring again. If it does fix the edit form, can make sure this fix is applied to the batch collection move and such.

Commit: 5fc0b451b926debda4fe3011811e34818eca4d80

**Comment by kjrawson** [comment]
That record seems fine now. Is there just a lag, is that what you are finding? We'll keep this ticket open for a bit in case it happens again. Thanks!

**Comment by scande3** [comment]
It wasn't saving the relationship to Solr for some reason (but it was being persisted in Fedora). I reload the object and resend the information to Solr at the end of the update to help ensure it is persisted there. Are you still seeing the issue?

**Comment by kjrawson** [comment]
Haven't seen it happen again yet. Thanks!
