### ISSUE TITLE
Search Results Error

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#92]
This search in an incognito window is giving me an error page:

https://www.digitaltransgenderarchive.net/catalog?utf8=%E2%9C%93&search_field=all_fields&q=metamorphosis

![error](https://cloud.githubusercontent.com/assets/15388345/19501256/fff5e008-9571-11e6-8aa6-ff6b7931edbe.jpg)

**Comment by scande3** [comment]
I added a check in the code for the case that caused this error. Let me know if you see it again. Thanks!

**Comment by kjrawson** [comment]
Thanks!
