### ISSUE TITLE
Display of page navigation in search results

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#93]
Hey, Steven.
No rush on this, but when you get a chance, can you fiddle with the display of the page navigation for search results? It would probably be best to have Previous, Page Numbers, Next. And if the buttons could be the same shape, that would be good, too. Thanks!

![navigation](https://cloud.githubusercontent.com/assets/15388345/19501406/5e1ac36e-9573-11e6-9606-7a19eb9dc582.jpeg)

**Comment by scande3** [comment]
It looks fine to me in Internet Explorer and Chrome. What browser and version are you using for this?

**Comment by kjrawson** [comment]
Okay, that's weird. I am using Chrome, but it looks fine now. I am glad I included the image so you know I am not completely crazy :)
