### ISSUE TITLE
May or may not be DTA related issue

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#95]
Hey, Steven.
I have been having some trouble with load times on my personal site: www.kjrawson.net. After doing all sorts of optimization stuff without any impact, I am thinking it's a DNS issue: https://intodns.com/kjrawson.net. Some similar issues are coming up with a DTA query: 
https://intodns.com/digitaltransgenderarchive.net

Do you think this might have something to do with the way we set up the DTA domain thru the same hosting account that I use for my personal site? I wonder if Bluehost changed some settings or something? Their help chat has been useless.

Thanks!

**Comment by scande3** [comment]
I don't think there is anything wrong with digitaltransgenderarchive.net as it comes up fairly quickly for me.

It doesn't seem to be DNS related for your personal site. The domain resolves fairly quickly. . . seems more likely to be an issue with whatever web host you are using for that content?

**Comment by kjrawson** [comment]
Thanks for your thoughts, Steven. It's helpful to know that it's not DTA-related. Have a great day!
