### ISSUE TITLE
Adding file sort for visibility

### ISSUE THREAD

**Issue by kjrawson** [CollegeOfTheHolyCross/dta_sufia#97]
Hi, Steven!
I am wondering if it would be possible to add an option to sort the back end file listing by visibility? This is the page I mean: https://www.digitaltransgenderarchive.net/dashboard/files

Thank you!

**Comment by scande3** [comment]
Added this. However, do know that "Institution Name" is "restricted" in the code (and sorts on that "r" value). As I can adjust how things are sorted, what is your preference for the three states ordering?

**Comment by kjrawson** [comment]
I am not sure if I fully understand your question, but I just checked the functionality and it looks great––that's exactly what I was hoping for. Thanks so much!
